### ISSUE TITLE
Create a record for the child at 29 days old (pregnancy outcome live birth outcome)

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#100]
Children can be registered directly into the child register from the Child Registration form, or, if they are registered at birth via the pregnancy outcome form, then a record for them in the child register is created at 29 days old. 

So, when Pregnancy Outcome = live birth and child is registered and when child's {age} = 29 days:
- [x] The child should be added to the top of the child register list
- [x] All the content from the Baby Details section of the Pregnancy Outcome form is used to create a child record in the same family as the mother. So the child should be added to the family members profile page as well.
- [x] The immunizations at birth from the pregnancy outcome form (if recorded) will be mapped to the medical history of the child. In other words, if birth immunizations were recorded in the pregnancy outcome form, then the birth immunizations task should be canceled in the child home visit, and the birth immunizations should appear already in the child's medical history when their record is created.
- [x] When the child is added to the child register, a home visit should become due for the child immediately.
- [x] We also need to save the Baby Details from the pregnancy outcome form to create an Edit Child Registration form for the child in their profile.

**Comment by cafootitt** [comment]
@msschroeder What is meant by the below:

>>  The child record will be mapped to a similar form as new children are added to family

**Comment by msschroeder** [comment]
@cafootitt When you register a child, they fill in the forms for a child U5 form. Then, this information is made available possibly to edit based on form filled. To enable this feature, the child added via PNC would have to be mapped to the child u5 registration form too?

**Comment by cafootitt** [comment]
@msschroder Ok, so what do the devs need to do for this point, exactly? I'm still not getting why this needs to be done.

**Comment by msschroeder** [comment]
@cafootitt Basically, the question becomes we need the baby from PNC added to the Child register. How is that going to be done? Do we want to have the fields in the Pregnancy Outcome for the Baby details mapped to the child U5 registration form?

**Comment by cafootitt** [comment]
I removed that line. This issue is about using the pregnancy outcome form to create the child, so the preg. outcome form is a child registration form as well. The last task "We also need to save the Baby Details from the pregnancy outcome form to create an Edit Child Registration form for the child in their profile." covers what you are referring to I believe.

**Comment by cafootitt** [comment]
I'm closing this and putting all clean up in this issue: https://github.com/OpenSRP/opensrp-client-chw-anc/issues/284
