### ISSUE TITLE
Design the text to go underneath the completed task in the PNC home visit

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#103]
We will need to implement the text be show beneath a task in the PNC home visit

For the PNC home visit, I'm using the google sheet again:
https://docs.google.com/document/d/1gnnqf8UUrC6doHEPoQNmQ-0G8lJ6tJH4D3TdodhhFZs/edit?usp=sharing

@rowo @cafootitt  Pls review and see if this makes sense before I assign it to the devs.

**Comment by msschroeder** [comment]
@rowo @cafootitt I have created a new issue for BA. Please close this @cafootitt once you have determined for WCARO

**Comment by cafootitt** [comment]
Ok
