### ISSUE TITLE
Implement the PNC home visit UI

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#104]
<img width="253" alt="Screen_Shot_2019-06-13_at_4_46_29_PM" src="https://user-images.githubusercontent.com/20777928/59673452-05e7a800-91ca-11e9-8b84-97eec1d79e24.png">

- [x] X or device back button takes you back to the woman's profile page after confirming form close dialog.
- [x] Submit button in top right is not active, greyed out, and cannot be tapped until all required tasks are completed. All tasks apart from Obs & Illness are required.
- [x] {first_name} {middle_name} {surname}, {age} - PNC Home Visit (NOTE: the name is the mother's name from the registration form)
- [x] Let's make sure we match the font, color, font size, etc. from the other two home visits (ANC and Child).

-----------------------------------------------------------------------------------------------
- BA no difference

**Comment by mberg** [comment]
We may have to figure out how to split this view between mother and child to accomodate if there are multiple children.

**Comment by msschroeder** [comment]
lgtm
