### ISSUE TITLE
Add danger sign asset to danger signs task in ANC home visit

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#109]
Add danger signs image from https://github.com/OpenSRP/opensrp-client-chw-anc/issues/18 issue to the info icon of danger signs question in ANC home visit.

**Comment by cafootitt** [comment]
Blocked by https://github.com/OpenSRP/opensrp-client-native-form/issues/232

**Comment by ellykits** [comment]
**Snapshot from Native Form**

![Screenshot_1562009254](https://user-images.githubusercontent.com/26865532/60461561-8e952800-9c4f-11e9-8871-10000becaa31.png)
![Screenshot_1562009246](https://user-images.githubusercontent.com/26865532/60461572-9654cc80-9c4f-11e9-9572-4ef6f4f28470.png)

**Comment by cafootitt** [comment]
lgtm
