### ISSUE TITLE
Design ANC medical history page

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw-anc#13]
For this one, I am thinking it would only include the following history:

- anc card received yes/no
- anc health facility visits:
-- ANC visit number and date
-- Weight
-- BP
-- Hb level
-- IFA received yes/no
-- Tests done: urine, hiv, syphilis
- TT immunization
- IPTp-SP doses

------------------------------------------------------------------------------------------------------
For this BA, we would need to adjust the history as not all values are collected. I would think of including the following:

- **Not in BA**: anc card received yes/no
- anc health facility visits:
- ANC visit number and date
-- **Not in BA** Weight
-- **Not in BA** BP
-- **Not in BA**Hb level
-- **Not in BA** IFA received yes/no
-- Tests done: urine, hiv, syphilis
- **Not in BA** TT immunization
- **Not in BA** IPTp-SP doses

**Comment by cagulas** [comment]
@rowo Unfortunately, this wasn't followed up on while I was on leave. We need this urgently now. Would you like to have a short discussion over the phone to talk through the content?

**Comment by rowo** [comment]
<img src="https://user-images.githubusercontent.com/1584163/58843353-1f241c80-8640-11e9-847d-c81f139d07ef.png" width="325">

<img src="https://user-images.githubusercontent.com/1584163/58843354-1f241c80-8640-11e9-91ed-0fde38904961.png" width="325">

**Comment by rowo** [comment]
I have to look at the multiple history issue again. I am thinking we'll need to do rows when there are multiple histories but maybe can get away with just stacking everything and adding overall sections. I don't know yet. This is one of the costs of doing the flexible history view. 

However, I don't think it impacts the view where you only have the single history, so what is in the previous comment probably still stands.

**Comment by cagulas** [comment]
Design is done, closing this issue.
