### ISSUE TITLE
Design ANC upcoming services page

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw-anc#14]
In reviewing the ANC services, it looks like ANC health facility visits, TT vaccination, and IPTp-SP doses are the only services on a separate schedule outside of the ANC home visit, so I would suggest that only these (or even simpler, only the ANC health facility visit schedule) would need to be shown on the upcoming services page. Can you work with this information to provide a mockup for the upcoming services page for ANC?

here's sample data from WHO ANC showing a real visit schedule. We are keeping the term "visit" instead of "contact" for Liberia I think.

Contact 1: | 10 wks
Contact 2: | 18 wks
Contact 3: | 26 wks
Contact 4: | 30 wks
Contact 5: | 34 wks
Contact 6: | 36 wks
Contact 7: | 38 wks
Contact 8: | 40 wks

------------------------------------------------------------------------------------------------------
- [ ] **BA is different**: The only service with a separate schedule is the ANC health facility visit schedule, which would be shown in the upcoming services page. I think the same mock-ups for WCARO will work for BA as well.

**Comment by cagulas** [comment]
@rowo Unfortunately, we need this urgently now.

**Comment by rowo** [comment]
@cagulas Should I add TT vaccination and IPTp-SP doses? If so, I guess I would just need that information.

**Comment by rowo** [comment]
@cagulas 

Here is a template screen for this. The actual content seems okay either way in terms of wording or including the non-contact items. Will the schedule be the same for everyone?

<img src="https://user-images.githubusercontent.com/1584163/58842954-7628f200-863e-11e9-995c-52f3142c7ee7.png" width="325">

**Comment by cagulas** [comment]
Thanks, @rowo I can work with this.
