### ISSUE TITLE
Count the PNC women and show updated number of clients in side menu

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#142]
For both WCARO and BA, we need to update the number of PNC clients shown in the side menu when a woman enters and leaves the PNC register.

Please see this issue that contains the rules for when the woman enters and leaves the PNC register. Please note, we are counting the number of PNC women only, not counting their babies in this count, even though the babies are included in the PNC profile with them.

**Comment by msschroeder** [comment]
BA: lgtm 
@cafootitt can you close if this looks good to you too?

**Comment by cafootitt** [comment]
1 Sept release - lgtm
