### ISSUE TITLE
Implement avatar or image of the woman in profile days 0 -28 days

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#143]
<img width="253" alt="Screen Shot 2019-06-13 at 9 52 37 AM" src="https://user-images.githubusercontent.com/20777928/59410275-1d392680-8dc1-11e9-8d3d-7958f577030b.png">

- [x] Take the avatar or image of the woman from their profile from their registration
- [x] Add a color of circle around the image dependent on the sex of the child (If {sex} = "Male", circle is blue. If {sex} = "Female", circle is pink)

-----------------------------------------------------------------------------------------------
**BA: No difference**

**Comment by msschroeder** [comment]
@cafootitt  @rowo I would want to increase the circle width around the avatar/photo on the profile page as it is relatively hard to see right now. What do you think? Below is an example
![Screenshot_20190731-115116](https://user-images.githubusercontent.com/20777928/62198552-82090a00-b38a-11e9-911d-821be07f2e10.png)

**Comment by msschroeder** [comment]
@manutarus If @cafootitt, @rowo are okay with this, I think we can close this. I will leave it open for now.

**Comment by rowo** [comment]
The circle I think is like 3px if what is shown is 1px.

**Comment by cafootitt** [comment]
@msschroeder We discussed this yesterday, and it needs to be the same as what's around the child avatar to be consistent. So, as Roger indicated, probably 3px then.

**Comment by msschroeder** [comment]
@manutarus Can we change the circle around the avatar to 3px then instead of 1 px as Carolyn and Roger discussed.

**Comment by cafootitt** [comment]
@manutarus I don't see this fixed in the version shared on 14 Aug. Can you please double-check that this was merged and should be in the latest releases?

**Comment by paulinembabu** [comment]
Closing the issue requires all the profiles to be merged

**Comment by cafootitt** [comment]
Will create a separate issue to improve the UI here, but closing for now.
