### ISSUE TITLE
Need to support accent characters

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#150]
See below. Accent characters are very common in the French language. We need to be able to support them in all the name fields.

![Screenshot_20190709-152038](https://user-images.githubusercontent.com/3488986/60901470-8d6e8700-a25d-11e9-95eb-9a2c058da610.png)

**Comment by cafootitt** [comment]
QA 30 July release:

This works for English but not for French, see below:

![Screenshot_20190730-084938](https://user-images.githubusercontent.com/3488986/62104077-2580ee80-b2a7-11e9-85e9-712e7dfdc92e.png)
![Screenshot_20190730-084840](https://user-images.githubusercontent.com/3488986/62104078-26198500-b2a7-11e9-964b-104849884010.png)

**Comment by rkodev** [comment]
@cafootitt has been resolved

**Comment by cafootitt** [comment]
lgtm
