### ISSUE TITLE
Persist date for the next health facility visit

### ISSUE THREAD

**Issue by ellykits** [OpenSRP/opensrp-client-chw-anc#154]
Since the next health facility visit date is generated dynamically with the rules engine, creating indicator based on the dynamic date is a bit complex.

**Comment by msschroeder** [comment]
@ellykits @rkodev Can you maybe provide reference to a document or issue on how this is done or could we have a quick discussion on this to better understand the implications. Because a few of things appear to be depend on this with in the home visit?

**Comment by rkodev** [comment]
@msschroeder we needed to save the 'next visit date' in the database so that reporting queries can identify if the visit is due or overdue.

**Comment by msschroeder** [comment]
@rkodev I have found that this seems to be working better, but is still a little wonky

**Comment by msschroeder** [comment]
lgtm
