### ISSUE TITLE
Create French version of the deworming icon

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#164]
Create new deworming icon with the French word for deworming: https://drive.google.com/open?id=1toBufFAir-W7u9MU_dSjUZ1gc0YCquPe

Label: "Déparasitage"

**Comment by rowo** [comment]
@cafootitt https://drive.google.com/open?id=1-X3-Peg7H6IXC4zXIvWHsK5JNFh4iUUf here you go

**Comment by cafootitt** [comment]
Excellent, thanks
