### ISSUE TITLE
Togo: Remove {essential_newborn_care} field from Pregnancy Outcome form

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#172]
Togo requested to remove this field from the Pregnancy Outcome form, since the CHW would not be able to ask this. Please keep this in for all other West African flavors.

**Comment by cafootitt** [comment]
@manutarus Let me adjust this issue slightly.

For Togo, we are removing the field altogether.
For the remaining West African countries, we are removing "No products applied to umbilical stump" answer choice only. You can see I have crossed out this answer choice in the data dictionary.

**Comment by cafootitt** [comment]
@manutarus Can you comment on this issue? I am still seeing this field in the Togo apk that was shared today (9 Aug release). This is in both the French and English version. Please can you explain what happened?

![Screenshot_20190809-122845_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/62769726-3cdb8b00-baa2-11e9-870a-e1daa5621cbf.jpg)

**Comment by ellykits** [comment]
Fixed as in the screenshot (For Togo)

![Screenshot_1567168394](https://user-images.githubusercontent.com/26865532/64020942-87997180-cb3b-11e9-9bcb-f604deee2300.png)
![Screenshot_1567168362](https://user-images.githubusercontent.com/26865532/64020948-89fbcb80-cb3b-11e9-83f1-56753ab10acd.png)

**Comment by cafootitt** [comment]
31 aug relese - lgtm
