### ISSUE TITLE
Implement danger signs task in home visit

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#18]
Danger signs is the first task to complete in the home visit. It is required to complete before the home visit can be submitted. It is always in the home visit.

Please look at the Danger Signs section in the ANC Home Visit tab in the [data dictionary](https://docs.google.com/spreadsheets/d/1hZrD3P8X3YAd-JvlXdT4TGKWJ87NlaLKjJlPrJZFwMY/edit#gid=102133992).

This will be a native form widget, but I have asked @rowo to create assets for the danger signs.

------------------------------------------------------------------------------------------------------
- [x] **BA is the same:** Please look at the Danger Signs section in the ANC Home Visit tab in the [data dictionary](https://docs.google.com/spreadsheets/d/1feKFVFtCZsGVzwEglbDZ4f5uP84F8wL2jwwXvfqUgP0/edit?usp=sharing).

**Comment by cagulas** [comment]
@rkodev Here is the danger signs asset from Roger. Let's put it in an info icon that the user can scroll through on the danger signs counseling question. This is for WCARO only. BA will have different assets to use.

![58898436-91404400-86c8-11e9-95ea-6c3bd2a3adce](https://user-images.githubusercontent.com/3488986/58936123-b475fc80-8777-11e9-9843-e97fa32ccb64.png)

**Comment by cagulas** [comment]
QA 6 June build:

- [ ] Pls see the 4 highlighted cells in the data dictionary for this task. We need to add the info icon with the image above. We also need to correct the relevance logic on the note and change the danger sign question to a select multiple. I think we want the danger signs to be shown in a checkbox list, not hidden in a spinner widget.

**Comment by msschroeder** [comment]
QA 6 June Build:
- [ ] In ANC Danger Signs, the second question, "Did the mother receive counselling on danger signs at the health facility recently?" is not readable on the screen.

**Comment by rkodev** [comment]
@msschroeder I have added an info icon to make the question readable in the spinner

**Comment by rkodev** [comment]
@cafootitt All the issues on the form have been addressed apart from the images. Could we move the images to be a separate issue after the current milestone?

**Comment by msschroeder** [comment]
@rkodev  Cool that sounds great!

**Comment by msschroeder** [comment]
@rkodev  Cool that sounds great!

**Comment by cafootitt** [comment]
Lgtm

I moved the last item into a new issue: https://github.com/OpenSRP/opensrp-client-chw-anc/issues/109.
