### ISSUE TITLE
Implement Kangaroo Mother Care (KMC) task

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#182]
- [x] Kangaroo Mother Care (KMC) is the 8th task in the WCARO PNC home visit. It is a required task for the CHW to record before the home visit can be submitted. 
- [x] It always appears in the PNC home visit (as long as the child is still in PNC) and if the child is low birthweight ({lbw} = "Yes")
- [x] See row 71 in PNC Home Visit tab in the [data dictionary](https://docs.google.com/spreadsheets/d/1hZrD3P8X3YAd-JvlXdT4TGKWJ87NlaLKjJlPrJZFwMY/edit#gid=1982829334)
- [x] Discussing with @rowo whether we can get an icon for this

**Comment by rowo** [comment]
https://drive.google.com/file/d/1-bGsA_ixtaZtOTqZjabMWwp4953PoqZs/view here's the kangeroo graphic

**Comment by cafootitt** [comment]
Thanks @rowo

**Comment by cafootitt** [comment]
@rkodev Can you confirm that this should be in the apk you shared on Aug 13th? I am not seeing the KMC task in either the French nor the English version.

**Comment by cafootitt** [comment]
2 Sept release - lgtm
