### ISSUE TITLE
Implement ANC counseling task in ANC home visit

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#19]
ANC counseling is the second task to complete in the home visit. It is required to complete before the home visit can be submitted. It is always in the home visit.

Please look at the ANC Counseling section in the ANC Home Visit tab in the [data dictionary](https://docs.google.com/spreadsheets/d/1hZrD3P8X3YAd-JvlXdT4TGKWJ87NlaLKjJlPrJZFwMY/edit#gid=102133992). The two cells in bright yellow in this section are still to be finalized by the client, so these will be replaced as soon as finalized.

This will be a native form widget, but I'd like to display the remaining visit dates for the woman in the "Importance of ANC visits" field, similar to https://marvelapp.com/3aj9f30/screen/41308925 from the WHO ANC app. Separate issue to be created for ANC health facility visit scheduling.

------------------------------------------------------------------------------------------------------
- Not in BA

**Comment by cagulas** [comment]
Pending tasks as of 6 June build:

- [ ] Visit dates need to be pre-populated in the note
- [ ] Pls replace the info icons in rows 18 and 24 in the data dictionary. These were finalized by the client.

**Comment by cafootitt** [comment]
lgtm
