### ISSUE TITLE
Cannot access PNC profile from ANC record moved based on pregnancy outcome form with stillbirth

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#190]
Reference #82 

- [x] App crashes when an ANC record is transitioned to PNC record when the pregnancy outcome form is filled.

To replicate: 
1. Open an ANC record
2. Fill in the pregnancy form and select still birth.
3. Submit the form.
4. ANC record has moved to PNC. 
5. Open the PNC record for same woman. 
6. App will crash.

**Comment by cafootitt** [comment]
@msschroeder This is fixed in the wcaro app, but there's a new issue where we're still assigning a child's name to the woman, which I'm putting into a new issue.

**Comment by msschroeder** [comment]
This is also fixed in the BA app.

**Comment by msschroeder** [comment]
lgtm
