### ISSUE TITLE
PNC profile page days 0-28, outcome of live birth incorrect profile text

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#192]
Reference #78 

- [ ] Child information should only display age once - {first_name} {middle_name} {surname}, {age}, F/M  ("F" if {sex} = "Female" or "M" if {sex} = "Male" from Preganancy Outcome form)

![Screenshot_20190801-113810](https://user-images.githubusercontent.com/20777928/62278696-44bb7f80-b451-11e9-8f9b-7c1390119ff6.png)

**Comment by cafootitt** [comment]
@msschroeder I looked at this issue, and it looks like someone created a kid with the name of "John Mau 0", so 0 is part of the name, not the age. I think some people create kids with names like this for easy testing, but it is confusing, I realize that.

What you could have considered/tested to validate whether this was an actual bug (for future testing purposes):
- The fact that the ages were not matching (0 and 1d), and that the 0 was missing the age unit, and the placement of the comma, give clues that the "0" is not an age but part of the child's name.
- Opening up the PNC home visit would allow you to see the child's full name to confirm if that's the actual name
- Looking at different PNC profiles to see whether age is double appearing elsewhere

Closing this.
