### ISSUE TITLE
Time unit is missing in the last visit row - all wcaro/ba flavors

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#202]
- [x] See "last visit 56 ago" is missing "days". 
- [ ] Please address in all flavors - wcaro and ba.

![Screenshot_20191002-133523](https://user-images.githubusercontent.com/3488986/62513615-5c19b480-b825-11e9-94ff-222d08fc1583.png)

**Comment by cafootitt** [comment]
@allan-allay This fails QA. I'm still seeing the same issue in the 31 aug release (both english and french versions)

![Screenshot_20191011-154513_CFC-RTM - Togo](https://user-images.githubusercontent.com/3488986/64076640-f3acde80-cccf-11e9-8fa5-3c84c8a8fc48.jpg)

**Comment by allan-allay** [comment]
Tested on the emulator and the time unit shows (in English)
![fixed_](https://user-images.githubusercontent.com/16164649/64099660-800fdd80-cd72-11e9-8d21-004c91162610.png)
Will also test on an Android device

**Comment by allan-allay** [comment]
After testing the **wcaro** and **ba** variants on an emulator and a Samsung device, the time unit appears fixed as in the screenshots shared above. 
If the issue still persists, I'd need some help recreating it

**Comment by cafootitt** [comment]
Ok, this does seem to be fixed, closing.
