### ISSUE TITLE
LMP date constraint only allows today's date to be entered

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#206]
In the latest release (9 Aug) of the Togo app, the constraint for LMP was updated incorrectly. It is only allowing me to put today's date as the LMP date. This is a really high priority issue to fix.

The constraint should be (which can also be found in the data dictionary):
<= {today} AND cannot be more than 50 weeks ago

This means that the user cannot enter an LMP date in the future nor can they enter an LMP date that is more than 50 weeks ago (e.g. if today is Aug 9, you cannot enter a date earlier than 24 Aug 2018).

**Comment by rkodev** [comment]
@cafootitt @msschroeder 
There was an issue with the integration of the latest core and native forms. We need to exclude some core config so to support the latest core.

**Comment by cafootitt** [comment]
Fixed in 13 Aug release
