### ISSUE TITLE
Physically challenged field is now missing on the French Preg outcome form

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#208]
- [x] Physically challenged field is now missing in the Pregnancy Outcome form, French version only.

![Screenshot_20190809-122845_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/62776069-3228f200-bab2-11e9-96c5-923c30b10dff.jpg)

**Comment by ellykits** [comment]
This is on Togo version, fix made on the rest of West Africa apps

![Screenshot_1567175772](https://user-images.githubusercontent.com/26865532/64029154-b2d88c80-cb4c-11e9-8190-b29249826b05.png)

**Comment by cafootitt** [comment]
QA 31 Aug release - lgtm
