### ISSUE TITLE
Implement ANC home visit UI

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#21]
<img width="332" alt="Screen Shot 2019-05-07 at 11 40 08 AM" src="https://user-images.githubusercontent.com/3488986/57285936-ef273f00-70bc-11e9-81b2-3cfdcdf31928.png">

- [x] X or device back button takes you back to the woman's profile page after confirming form close dialog.
- [x] Submit button in top right is not active, greyed out, and cannot be tapped until all required tasks are completed. All tasks apart from Obs & Illness are required.
- [x] {first_name} {middle_name} {surname}, {age} - ANC Home Visit

------------------------------------------------------------------------------------------------------
- BA no difference

**Comment by cagulas** [comment]
QA 6 June release:

- [ ] Back button does not show a confirm form close dialog yet.
- [ ] UI fixes below:

<img width="803" alt="Screen_Shot_2019-06-07_at_10_58_00_AM" src="https://user-images.githubusercontent.com/3488986/59090273-0738eb00-8915-11e9-9533-617e9e9eafce.png">

**Comment by msschroeder** [comment]
QA June 6 build:
![Screenshot_20190610-201205](https://user-images.githubusercontent.com/20777928/59250709-b422a900-8c30-11e9-9d9f-f6a673dc4f23.png)

**Comment by rkodev** [comment]
![Screenshot_1560417423](https://user-images.githubusercontent.com/43806892/59420444-92aef200-8dd5-11e9-8284-e011934517b3.png)
@cafootitt updated design

**Comment by rkodev** [comment]
![Screenshot_1560417576](https://user-images.githubusercontent.com/43806892/59420478-a0647780-8dd5-11e9-9bb7-bb6fa18cae24.png)
@msschroeder updated design

**Comment by rkodev** [comment]
![Screenshot_1560419223](https://user-images.githubusercontent.com/43806892/59422655-672e0680-8dd9-11e9-9b33-e4372aaddb00.png)
@cafootitt

**Comment by cafootitt** [comment]
lgtm

**Comment by msschroeder** [comment]
@rkodev Lgtm too

**Comment by cafootitt** [comment]
lgtm in 19 June release
