### ISSUE TITLE
PNC Visit button should be shown immediately after PNC registration (if relevant)

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#210]
Right now, the PNC woman row appears immediately in the PNC register list view, but the Visit button does not. One has to re-visit the page for the visit button to show.

Let's make it so that the visit button appears immediately as well (If relevant, meaning if a visit is actually due).

![Screenshot_20190814-151139_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/63020236-38e6a900-bea6-11e9-9f21-36c710e2efa9.jpg)

**Comment by paulinembabu** [comment]
This was Fixed after the Pnc Schedule issue was fixed.

**Comment by cafootitt** [comment]
2 Sept release - lgtm
