### ISSUE TITLE
Implement ANC card task in ANC home visit

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#22]
ANC card is the fourth task to complete in the home visit. It is required to complete before the home visit can be submitted. It appears in the home visit always until it is marked as given.

Please look at the ANC card section in the ANC Home Visit tab in the [data dictionary](https://docs.google.com/spreadsheets/d/1hZrD3P8X3YAd-JvlXdT4TGKWJ87NlaLKjJlPrJZFwMY/edit#gid=102133992). 

This will be a single question widget (similar to Vitamin A, Deworming, etc.). We don't have an icon for this yet. 

@rowo Can you create one please?

------------------------------------------------------------------------------------------------------
- Not in BA

**Comment by rowo** [comment]
@cagulas do you have a pic of the ANC card handy?

**Comment by cagulas** [comment]
@rowo No, we don't have one. I'd just make it a generic square-looking card. We'll be using the same icon for the child health card as well, so it should be generic to any person and health area.

**Comment by cagulas** [comment]
@rowo We now urgently need this as we try to wrap up child module and implement anc module. Mahmud is using the deworming icon as a placeholder now. When can you get this to us?

**Comment by rowo** [comment]
@cagulas https://drive.google.com/file/d/1P-n-BUAfFL6-Oqlb4rALH2e2ZarVUe1L/view Does this work?

**Comment by cagulas** [comment]
Works for me, thanks!

**Comment by cagulas** [comment]
@mahmud6390 Please use this icon for the vaccine card.

**Comment by mahmud6390** [comment]
added in this PR https://github.com/OpenSRP/opensrp-client-chw/pull/376

**Comment by cagulas** [comment]
QA 6 June build:

- [ ] Let's change the title of the dialog to "ANC card received" instead of "ANC card task"

All else looks good!

**Comment by cafootitt** [comment]
lgtm
