### ISSUE TITLE
A pregnant mother can be reregistered and overwrite data

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#222]
- [x] Once a pregnant mother is registered in ANC, the drop down from her profile (family and ANC register) must not allow her to register as a pregnant mother again. 

Issue:
A pregnant mother can be registered multiple times and her record can be overwrote with the new filled record.

Replicate:
1. Go to the family profile
2. Go to the profile of a woman between 15 - 49
3. Fill in the ANC Registration
4. Go to ANC Register - the woman should be there
5. Go back to family profile
6. Repeat steps 2 - 4.
7. Woman will appear with the most recent data

Linked to #65

**Comment by cafootitt** [comment]
31 Aug release - lgtm.
This should be fixed in all CHW versions, so I'm closing.
