### ISSUE TITLE
ANC Schedule changes incorrectly

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#225]
- [ ] The ANC health facility visit does not appear to be working correctly for health facility visits in months where the CHW visit the family, but there is no ANC health facility visit.

Explanation
- An ANC woman has a LMP of May 7, 2019 and today is August 20th, 2019. She would be 15 weeks. 
- Her 1st ANC health facility visit would be August 20, 2019. 
- She did have that health facility ANC 1st visit on August 20th. 
- Her next visit is October 12, 2019 (with the current service schedule)
- Her CHW does a home visit in September. Since her next health facility visit is not until October 12th, she enters that the woman did not go to the health facility visit. 
- Her CHW does a home visit in October after her supposed ANC 2 health facility visit (August 12th), but the new due date of the ANC 2 health facility visit is November 9th.
- Why is this? @rkodev @manutarus @paulinembabu @cafootitt

**Comment by cafootitt** [comment]
@msschroeder Ok, if I'm following this correctly, you're saying that during the home visit in October, the ANC 2 health facility visit should show the October 12th due date, not the November 9th due date that's showing now. Is that correct?

**Comment by msschroeder** [comment]
@cafootitt That is what I am trying to say. Essentially, it skips the October ANC visit and put it in the next month.

**Comment by msschroeder** [comment]
@rkodev @paulinembabu This is the issue I brought to your attention this week:

From our conversation, the next ANC health facility visit is based on the date where the ANC health facility was yes. However, it appears to use the date of the last ANC CHW home visit.

Replicate:
1. Register a woman's pregnancy (i.e. September 18, 2019 at 0 weeks - meaning a HF visit every 8 weeks)
2. Do an ANC home visit the same day (i.e. September 18, 2019) and register the ANC visit as today (i.e. Sept 18, 2019). 
3. The next HF visit is like Nov 13th, but I will still do a monthly CHW home visit in October (i.e. October 15th, 2019)
4. I do a monthly home visit in November (i.e. November 15th) and I see that the next ANC HF visit says is December - 8 weeks after the home visit in October. This leads me to believe the home visit schedule visit is being used.

**Comment by msschroeder** [comment]
lgtm
