### ISSUE TITLE
ANC Medical History does not record the date of health facility visit but the home visit

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#227]
- [x] ANC health facility date should use the health facility visit date `anc_hf_visit[1-8]_date` not the CHW home visit date `anc_visit_date` in the medical history.
- [x] This issue is occurring in both the wcaro and ba flavors, so please update in all flavours.

Currently, the opposite is occuring. For example, the ANC health facility visit 1 was done on August 5, 2019, but the medical history shows August 6th, 2019

![Screenshot_20191025-162815 (1)](https://user-images.githubusercontent.com/20777928/63407696-d0dc1980-c3f5-11e9-9254-5fc2e22eeb91.jpg)

**Comment by cafootitt** [comment]
31 aug release - lgtm
