### ISSUE TITLE
ANC Medical History ANC Health Facility visits should have consistent spacing for tests

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#228]
- [x] For an ANC health facility visit, the tests done should be separated by a comma space instead of space, comma, space. Shown below.

![Screenshot_20191025-162815 (1)](https://user-images.githubusercontent.com/20777928/63407914-73949800-c3f6-11e9-9a97-1c9460e9f03b.jpg)

**Comment by cafootitt** [comment]
31 Aug release - this should be fixed.
