### ISSUE TITLE
Implement ANC [1-8] health facility visit task in ANC home visit

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#23]
ANC [1-8] health facility visit is the fifth task to complete in the home visit. It is required to complete before the home visit can be submitted. It appears in the home visit based on the ANC health facility visit schedule (separate issue to be created).

Please look at the ANC [1-8] health facility visit section in the ANC Home Visit tab in the [data dictionary](https://docs.google.com/spreadsheets/d/1hZrD3P8X3YAd-JvlXdT4TGKWJ87NlaLKjJlPrJZFwMY/edit#gid=102133992). 

This will be a native form widget.

------------------------------------------------------------------------------------------------------
**BA is a little different**

ANC [1-8] health facility visit is the **second** task to complete in the home visit. It is required to complete before the home visit can be submitted. It appears in the home visit based on the ANC health facility visit schedule (separate issue to be created).

Please look at the ANC [1-8] health facility visit section in the CHW 2 - ANC HH Visit tab in the [data dictionary](https://docs.google.com/spreadsheets/d/1feKFVFtCZsGVzwEglbDZ4f5uP84F8wL2jwwXvfqUgP0/edit?usp=sharing). 

This will be a native form widget.

**Comment by cagulas** [comment]
QA 6 June build:

- [ ] Pls see all cells highlighted in purple in the data dictionary for this task. The visit date field is only allowing today's date to be entered, and both BP fields should not allow decimal inputs.

**Comment by msschroeder** [comment]
QA 6 June Build (BA)

- [ ] The field `anc_hf_visit[1-8]` is not readable on the screen. Also, the visit date only shows today and yesterdays's date. P

**Comment by rkodev** [comment]
@msschroeder I've added an info icon to help with readability for the drop down spinner.

**Comment by msschroeder** [comment]
@rkodev Cool. I will wait to see the next release

**Comment by cafootitt** [comment]
This looks good to me.

The info icons did not need to be added. Looks like someone took the "description" column in the data dictionary to mean the info icon column. Would be good to remove them, so they aren't a distraction, but ok leaving them for now, since we're on a tight deadline.

Megan, the cut off issue is an issue with the form library itself. There's an issue created for it. I don't know when it will be picked up.

**Comment by msschroeder** [comment]
QA 19 June Build:
- [ ] The app crashes/slows down when I select all the tests and all the immunizations possible and I cannot submit the task

**Comment by cafootitt** [comment]
30 June release: - [ ] The field LLIN_given appears for all ANC health facility visits but it should only appear for the first one, is not addressed yet.

**Comment by cafootitt** [comment]
Created a new issue for the last item: https://github.com/OpenSRP/opensrp-client-chw-anc/issues/128.

The checkbox issue has been resolved.
