### ISSUE TITLE
Update the choice option for pregnancy outcome form

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#230]
- [x] Update the first choice option for the question `delivery_hf` in the pregnancy outcome form. [Data dictionary](https://docs.google.com/spreadsheets/d/1feKFVFtCZsGVzwEglbDZ4f5uP84F8wL2jwwXvfqUgP0/edit?usp=sharing), Tab CHW 4 - Pregnancy outcome form, row 26 (question), row 28 (choice option to update)

**Comment by cafootitt** [comment]
Megan updated the json English version, moving to QA.
