### ISSUE TITLE
Home Visit Task text incorrect

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#234]
Text under PNC home visit tasks after completed is incorrect:
- [ ] **PNC 1-4 health facility visit**
If {pnc_visit_1-4} = "No":
"Visit not done"
If {pnc_visit_[1-4]} = "Yes":
"Date: {pnc_hf_visit[1-4]_date}"
"Vitamin A received: {vit_a_mother}" (only first visit)
"IFA tablets received: {ifa_mother}" (only first visit)

- [ ]  **Family planning**
[1st row] "Couselling: {fp_counseling} ᛫ Period received: {fp_period_received}". 
[2nd row] "Method chosen: {fp_method} ᛫ Start date: {fp_start_date}"

- [ ] **Immunisations (at birth)** uses choice options not labels. For example OPV0 is opv_0 and BCG is bcg

**Comment by msschroeder** [comment]
QA Nov 18:
- [ ] All indicators are included. However, the following below are not translated. @paulinembabu Is this because they have to be translated in transifex?

"Vitamin A received: {vit_a_mother}" (only first visit)
"IFA tablets received: {ifa_mother}" (only first visit)

**Comment by paulinembabu** [comment]
I added some strings on the Chw APP. They need to be translated. I was to communicate that. Sorry

**Comment by msschroeder** [comment]
QA November 18:
- [ ] If the visit is not done for the PNC visits, the text is not added.

**Comment by msschroeder** [comment]
QA Jan 31 Build:
PNC Health Visit looks good
Immunizations look good 
Family Planning text is not yet working - I will create a new issue for this.
