### ISSUE TITLE
Implement ANC health facility visit schedule in ANC home visit

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#24]
The ANC health facility visit schedule is below:
https://docs.google.com/spreadsheets/d/1Enilx-fCMbNmEcprzm5zJdMlykoL7moXI6gQCZIUIQ4/edit#gid=643795501

It is the same as the WHO ANC reference app, implemented using the rules engine. Please speak with ben or elly to copy over the schedule into this app.

This schedule dictates whether the ANC health facility visit task (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/23) is triggered in the ANC home visit. If a health facility visit is currently due or overdue, the task will appear. Use the due date of the health facility visit as the task due date.

------------------------------------------------------------------------------------------------------
**No difference in BA**

**Comment by cagulas** [comment]
Did not QA, as this isn't implemented yet.

**Comment by msschroeder** [comment]
QA 18 June Build:
- [ ] The visit number in the task ANC [1 - 8] health facility visit does not change from month to month regardless if I filled in the previous months.

Note: The dates for next visit appear to be working well though.

**Comment by cafootitt** [comment]
QA 19 June release:

This is pretty close. For some reason, the days seem to be one day off though. See below.

**Expected:**
Woman: Margaret Otala, 30
LMP: March 20, 2019
EDD: Dec 27, 2019

ANC 1: June 20 (GA: 13 weeks 1 day)
ANC 2: Aug 15 (GA: 21 weeks 1 day)
ANC 3: Sept 26 (GA: 27 weeks 1 day)
ANC 4: Oct 24 (GA: 31 weeks 1 day)
ANC 5: Nov 21 (GA: 35 weeks 1 day)
ANC 6: Dec 5 (GA: 37 weeks 1 day)
ANC 7: Dec 19 (GA: 39 weeks 1 day)
ANC 8: Dec 25 (GA: 40 weeks)

There should be **NO** visits scheduled past the woman's EDD.

**Actual:**
![Screenshot_20190620-153216](https://user-images.githubusercontent.com/3488986/59850219-60bc0380-9372-11e9-9073-8f972f291c81.png)

**Comment by cafootitt** [comment]
@rkodev Did you address the issue here about the due dates being 1 day off? I'm noticing this might still be an issue.

**Comment by msschroeder** [comment]
@rkodev The same issue I reported previously is still an issue:
QA 18 June Build:

 The visit number in the task ANC [1 - 8] health facility visit does not change from month to month regardless if I filled in the previous months.

Note: The dates for next visit appear to be working well though.

**Comment by msschroeder** [comment]
@rkodev I am finding that this feature appears to be working weird. I was wondering if we could meet to discuss how this is working. I am wondering if this is just not working because of the form and how it is set up

**Comment by cafootitt** [comment]
The issue with the days being one day off is fixed, so I'm closing this. I think the remaining issues around updating the visit schedule will be covered in issues https://github.com/OpenSRP/opensrp-client-chw-anc/issues/154 and https://github.com/OpenSRP/opensrp-client-chw-anc/issues/152

**Comment by msschroeder** [comment]
@rkodev @cafootitt This is still working weird in BA. Maybe I can discuss with either of you?

**Comment by cafootitt** [comment]
@msschroeder Ok let's discuss. How is this different from WCARO? Because it should be the same implementation in both. Let me stop by after this meeting.

**Comment by msschroeder** [comment]
@cafootitt I scheduled a quick meeting with you both in tomorrow. If we had time today that would be great!
