### ISSUE TITLE
Fix ANC register list page after registering a new pregnant woman

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#242]
When registering a pregnant woman, the ANC register list changes, i.e. a new QR code button appears in the bottom navigation menu, all demographic info disappears for all women, the due filter button is replaced with another button. Have shown this to Pauline and Ronald.

When you revisit the ANC register page, it appears normally again.

@paulinembabu Assigning to you, since you indicated you might know what's happening here.

This is the 23 August Togo release.

**Comment by paulinembabu** [comment]
This was fixed. It will be included in today's release after all the changes have been merged.

**Comment by cafootitt** [comment]
31 Aug release - lgtm
