### ISSUE TITLE
Implement TT [1-5] immunization task in ANC home visit

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#25]
TT [1-5] immunization is the sixth task to complete in the home visit. It is required to complete before the home visit can be submitted. It appears in the home visit based on the TT vaccination schedule shown in the data dictionary (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/26).

Please look at the TT [1-5] immunization section in the ANC Home Visit tab in the [data dictionary](https://docs.google.com/spreadsheets/d/1hZrD3P8X3YAd-JvlXdT4TGKWJ87NlaLKjJlPrJZFwMY/edit#gid=102133992). 

This will be widget similar to Vitamin A, deworming, where the user records if dose was given or not. Icon to use is the form-Immunization_xxhdpi.png in the icon folder: https://drive.google.com/drive/u/1/folders/1XMVd5PJEZEanMs57tBgEWbhVJbRBNYG3

------------------------------------------------------------------------------------------------------
**NOT in BA**

**Comment by cagulas** [comment]
QA 6 June build:

We need to shrink the size of the icon here to make sure the date widget does not get cut off. @rowo Do you have advice on this one?

![Screenshot_20190607-115002](https://user-images.githubusercontent.com/3488986/59092635-bfb55d80-891a-11e9-80ab-11ead0108c5f.png)

**Comment by rowo** [comment]
@rkodev I can trim the top/bottom transparent parts off images if that would make placement and sizing more flexible for you. Right now all of these types of images are the same size.

**Comment by rkodev** [comment]
@cafootitt @rowo would it be okay if I make the entire view scrollable instead of having the option buttons fixed at the bottom of the screen?

**Comment by cafootitt** [comment]
@rowo Can I pass this question to you? I think it would be nice to keep them fixed to the bottom and prevent scrolling for these one question service widgets if possible.

**Comment by rowo** [comment]
@rkodev Fixed is preferred. Reducing the image size should be the first option. For something with only a date input and a one-line label, I feel like no scrolling should be doable.

**Comment by rkodev** [comment]
@rowo opted to resize the image and have the buttons fixed

**Comment by cafootitt** [comment]
lgtm
