### ISSUE TITLE
Fix actions following Pregnancy Outcome of "Miscarriage" or "Other"

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#266]
When you fill out a Pregnancy Outcome form with outcome of "Miscarriage" or "Other", the following actions should happen:

- The ANC record should be removed from the ANC register list (not happening currently)
- The user should be redirected to the family register list (not happening currently - the user is redirected to the PNC register list instead)
- The ANC client count in the left navigation drawer should tick down by 1 (not currently happening)
- The ANC pregnant woman icon should be removed from the family register page (not currently happening, the purple pregnant icon still displays for that family)

@msschroeder Are you experiencing these same errors in BA?

**Comment by msschroeder** [comment]
In BA, only one is affected:

- The user should be redirected to the family register list (not happening currently - the user is redirected to the PNC register list instead) - This is also NOT working

**Comment by cafootitt** [comment]
Please work on https://github.com/OpenSRP/opensrp-client-chw-anc/issues/326 with this issue, since they're related.

**Comment by cafootitt** [comment]
QA V1.0.6

Everything works, apart from the fact that the blue PNC icon now appears for the family, when it shouldn't.

![Screenshot_20191003-232557_CFC-RTM - Togo](https://user-images.githubusercontent.com/3488986/66169031-08e99580-e60d-11e9-94c6-a51a5afc5bf0.jpg)

Follow the steps above to replicate.

**Comment by cafootitt** [comment]
V1.0.6 lgtm
