### ISSUE TITLE
Implement IPTp-SP [1st, 2nd, 3rd] dose task in ANC home visit

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#27]
IPTp-SP [1st, 2nd, 3rd] dose is the seventh task to complete in the home visit. It is required to complete before the home visit can be submitted. It appears in the home visit based on the IPTp-SP schedule shown in the data dictionary.

Please look at the IPTp-SP [1st, 2nd, 3rd] dose section in the ANC Home Visit tab in the [data dictionary](https://docs.google.com/spreadsheets/d/1hZrD3P8X3YAd-JvlXdT4TGKWJ87NlaLKjJlPrJZFwMY/edit#gid=102133992). 

This will be widget similar to Vitamin A, deworming, where the user records if dose was given or not. We don't have an icon for this yet.

@rowo Can you make one?

------------------------------------------------------------------------------------------------------
**NOT in BA**

**Comment by rowo** [comment]
@cagulas any idea for an icon here? Perhaps something from what Unicef shared?

**Comment by cagulas** [comment]
@rowo https://www.google.com/search?q=sulfadoxine-pyrimethamine+tablets&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiPhpTexcLiAhUIrxoKHaODAVUQ_AUIDigB&biw=1423&bih=792. It is your standard-looking tablet, so along the lines of the deworming tablet icon, but this is usually a round tablet I believe.

**Comment by rkodev** [comment]
@rowo when can we get the image for this?

**Comment by rowo** [comment]
@cagulas https://drive.google.com/file/d/1Vlnh-F_SVyoHTCU13RAQCXUFC3aJxzbn/view does this blister pack work for general circle pills? cc @rkodev

**Comment by cagulas** [comment]
I think it looks good, but let me swing it past Hawi and his team. Thanks. @rkodev I think it's ok to implement this. I will let you know if there are any objections from the client.

**Comment by rkodev** [comment]
@rowo thanks.

**Comment by cagulas** [comment]
QA 6 June build:

- [ ] Same issue as TT vaccination. We need to shrink the size of the icon so that the date widget does not get cut off.

![Screenshot_20190607-115529](https://user-images.githubusercontent.com/3488986/59092945-67329000-891b-11e9-9e49-7a26506ad008.png)

**Comment by rkodev** [comment]
![Screenshot_1560420213](https://user-images.githubusercontent.com/43806892/59423878-af4e2880-8ddb-11e9-91d9-527a5c1ae36b.png)
@cafootitt I reduced the image slightly to make it fit in 5' screen and above. For screens smaller than 5' it will be scrollable

**Comment by cafootitt** [comment]
lgtm

**Comment by cafootitt** [comment]
lgtm
