### ISSUE TITLE
Implement IPTp-SP [1st, 2nd, 3rd] dose schedules

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#28]
There are 3 doses of IPTp-SP that should be given to a woman in pregnancy. Please implement the schedule logic that you find in the [data dictionary](https://docs.google.com/spreadsheets/d/1hZrD3P8X3YAd-JvlXdT4TGKWJ87NlaLKjJlPrJZFwMY/edit#gid=102133992), IPTp-SP [1st, 2nd, 3rd] dose section of the ANC Home Visit tab.

------------------------------------------------------------------------------------------------------
**NOT in BA**

**Comment by cagulas** [comment]
QA 6 June build:

- [ ] I'm unable to QA the schedules, because the due dates are not appearing underneath the task name in the home visit page.

**Comment by cafootitt** [comment]
QA 19 June release:

- [ ] The first dose passes QA. It became due/overdue on the correct dates. The 2nd dose also appeared with the correct due date one month later; however, when I actually open up the widget to record the dose, the page still says 1st dose.
- [ ] Also, strangely, when I tap on the "Save" button, it's as if the date doesn't get registered, because I return to home visit page, and no matter what date I select and save, it gets recorded as Not given. See screenshots below:

1) 2nd dose with correct due date appears:
![Screenshot_20190801-141538](https://user-images.githubusercontent.com/3488986/59845526-4b40dc80-9366-11e9-88c1-e868a8f6a655.png)

2) Opening the widget, the page still references 1st dose. It should say when was 2nd dose given (and the header should also say 2nd dose instead of 1st dose):

![Screenshot_20190801-141607](https://user-images.githubusercontent.com/3488986/59845598-6e6b8c00-9366-11e9-9f63-9d4c7262d510.png)

3) Even when I select Save, it gets recorded as Not given. So there is no way to record 2nd dose right now:
![Screenshot_20190801-141625](https://user-images.githubusercontent.com/3488986/59845634-817e5c00-9366-11e9-8a1d-f6f4aba4901f.png)

**Comment by cafootitt** [comment]
Can't QA because of this issue: https://github.com/OpenSRP/opensrp-client-chw-anc/issues/152

**Comment by cafootitt** [comment]
I'm closing this. I'm still unable to QA the full schedule, because dose 1 is still re-appearing, but I'll close this and QA and create a new issue if there's a problem with the schedule.
