### ISSUE TITLE
Replace person avatars for ANC and PNC women in family members page

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#288]
Right now, both ANC and PNC women in the family members page are represented by the same generic person avatar as other adult members, making it difficult to identity which women are ANC or PNC in the family.

- [x] Let's use the below icon for ANC women (see next comment)

- [x] Let's use the below icon for PNC women:
![rowavatar-pnc](https://user-images.githubusercontent.com/3488986/64613017-d36ed500-d3dd-11e9-9b34-bb347b385680.png)

- [x] Switch the generic person avatar to ANC avatar when ANC registration form is filled in
- [x] Switch ANC avatar back to generic person avatar when Pregnancy Outcome form is filled with outcome of Miscarriage or Other
- [x] Switch ANC avatar to the PNC avatar when Pregnancy Outcome form is filled in with outcome of Live birth or Stillbirth
- [x] Switch PNC avatar back to the generic person avatar when PNC record is closed (which is delivery date + 60 days)

**Comment by rowo** [comment]
@cafootitt can you see if this will work for ANC?

![rowavatar-anc](https://user-images.githubusercontent.com/1584163/64736282-4ea4b980-d4b8-11e9-937a-61bbc26a408f.png)

**Comment by allan-allay** [comment]
@cafootitt Should we also change the avatars on the member profile so that for ANC or PNC woman profile the avatar is either the ANC or PNC one for consistency?

**Comment by cafootitt** [comment]
I think that makes sense, @allan-allay. Thanks.

**Comment by cafootitt** [comment]
@allan-allay 
I'm seeing these new avatars in the individual profile pages, but I'm not seeing it in the family members page. They should appear there as well.

**Comment by cafootitt** [comment]
Looks great, this is really helpful for testing and demoing the app too!

RC 1.0.8 - lgtm
