### ISSUE TITLE
Implement Observations & Illness - optional task in ANC home visit

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#29]
Observations & Illness - optional is the eigth task to complete in the home visit. It is NOT required to complete before the home visit can be submitted. It always appears in the home visit.

Please look at the Observations & Illness - optional section in the ANC Home Visit tab in the [data dictionary](https://docs.google.com/spreadsheets/d/1hZrD3P8X3YAd-JvlXdT4TGKWJ87NlaLKjJlPrJZFwMY/edit#gid=102133992). 

This will be a native form widget, same as what's already in the child module.

------------------------------------------------------------------------------------------------------
**BA is slightly different than WCARO**

Observations & Illness - optional is the seventh task to complete in the home visit. It is NOT required to complete before the home visit can be submitted. It always appears in the home visit.

Please look at the Observations & Illness - optional section in the ANC Home Visit tab in the [data dictionary](https://docs.google.com/spreadsheets/d/1hZrD3P8X3YAd-JvlXdT4TGKWJ87NlaLKjJlPrJZFwMY/edit#gid=102133992). 

Please note the content is slightly different for BA

This will be a native form widget, same as what's already in the child module.

**Comment by cagulas** [comment]
QA 6 June 2019:

- [ ] Check the data dictionary fields highlighted in bright purple. I can only select today's date for the date field.
- [ ] The confirm form close dialog should not appear when the user goes back

**Comment by msschroeder** [comment]
QA 6 June Build:
This works as expected in BA

**Comment by cafootitt** [comment]
lgtm
