### ISSUE TITLE
Implement icon status for completed tasks in the ANC home visit

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw-anc#30]
- [x] if {danger_signs_counseling} = "Yes", then green check, otherwise yellow
- [x] if {anc_counseling} = "Yes" and {birth_hf_counseling} = "Yes" and {nutrition_counseling} = "Yes", then green check, otherwise yellow
- [x] if {sleeping_llitn} = "Yes", then green check, otherwise yellow
- [x] if {anc_card} = "Yes", then green check, otherwise yellow
- [x] if {anc_hf_visit[1-8]} = "Yes", then green check, otherwise yellow
- [x] if {tt[1-5]_date} is recorded, then green check, otherwise yellow
- [x] if {iptp[1-3]_date} is recorded, then green check, otherwise yellow
- [x] if Observations & Illness - optional task is filled in, then green check, otherwise, leave blank

------------------------------------------------------------------------------------------------------
BA is similar, but slightly different due to different tasks

- [x] if {danger_signs_counseling} = "Yes", then green check, otherwise yellow
- [x] if {anc_hf_visit[1-8]} = "Yes", then green check, otherwise yellow
- [x] if {fam_planning} = "Yes", then green check, otherwise yellow
- [x] if {nutrition_status} is recorded, then green check, otherwise yellow
- [x] if {counselling_given} is recorded, then green check, otherwise yellow
- [x] if {fam_llin} = "Yes" and {llin_2days} = "Yes" and {llin_condition} = "Okay", then green check, otherwise yellow
- [x] if Observations & Illness - optional task is filled in, then green check, otherwise, leave blank
- [x] if Remarks/Comments - optional task is filled in, then green check, otherwise, leave blank

**Comment by cagulas** [comment]
QA 6 June build:

- Danger signs - OK
- ANC counseling - OK
- Sleeping under LLITN - OK
- ANC card - OK
- ANC health facility visit - OK
- TT immunization - OK
- IPTp-SP dose - OK
- Obs & Illness - OK

Lgtm!

**Comment by msschroeder** [comment]
QA 6 June build:
All is good for BA
