### ISSUE TITLE
IPTp-SP dose and PNC health facility visit tasks not saving

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#305]
Steps to replicate (IPTp-SP dose task):

1. Open an ANC woman's profile and open the ANC home visit (make sure IPTp-SP dose is a due task that appears in the home visit)
2. Complete the home visit, including the IPTp-SP dose task.
3. Save the home visit.
4. On the woman's profile page, click on the Edit button to re-open the ANC home visit you just submitted.
5. You'll see that the IPTp-SP dose task is blank again instead of showing the data you entered.

Steps to replicate (PNC health facility visit task):

1. Open a PNC woman's profile and open the PNC home visit (make sure PNC health facility visit is a due task in the home visit)
2. Complete the home visit, including the PNC health facility visit task.
3. Save the home visit.
4. On the woman's profile page, click on the Edit button to re-open the PNC home visit you just submitted.
5. You'll see that the PNC health facility visit task is blank again instead of showing the data you entered.

**Comment by cafootitt** [comment]
QA V1.0.4:

This is working for the PNC health facility visit task, but not the IPTp-SP dose task. 

Steps to replicate:
- Open an ANC woman's profile and open the ANC home visit (make sure IPTp-SP dose is a due task that appears in the home visit)
- Complete the home visit, including the IPTp-SP dose task.
- Save the home visit.
- On the woman's profile page, click on the Edit button to re-open the ANC home visit you just submitted.
- You'll see that the IPTp-SP dose task is blank again instead of showing the data you entered.

This was tested on the French version.

**Comment by allan-allay** [comment]
I wasn't able to recreate this on the emulator in the English and French versions of the app. 
So I'll try on an actual device.

**Comment by cafootitt** [comment]
@allan-allay I can show you today when you get in.

**Comment by cafootitt** [comment]
lgtm
