### ISSUE TITLE
Marking ANC visit not done is not updated in family profile page, due tab, or activity tab

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#309]
To replicate:

- Find a family that has a pregnant woman who has an ANC home visit due
- Go to the woman's profile page and mark the visit not done
- Go back to the family profile page. You'll notice that the ANC home visit task is still due in the Due tab.

#### To pass QA, the following should happen when you mark an ANC home visit as not done:
- [x] The blue/red dot beside the woman's profile picture on the family profile page should be removed
- [x] The ANC home visit in the Due tab should be removed
- [x] In the Activity tab, there should be a row that appears saying the ANC home visit was not done this month (this is working ok right now)
- [x] On the family register list page, the number of due tasks for the family should tick down by 1 (if this was the only remaining due/overdue task for the family left, then the status should change to the "Tasks not done" status)
- [x] On the first of the next calendar month, the ANC home visit status should change to the **overdue** state, i.e, the red dot should appear next to the woman's avatar in the family profile page, the overdue ANC home visit task should appear in the Due tab, and on the family register list page, the number of due tasks should tick up by 1.

**Comment by AnnieMungai** [comment]
Liberia CFC Monitor App Version: 0.1.9 (6th Dec 2019)

Looks good.
