### ISSUE TITLE
IPTp-SP 2 dose is being skipped in the ANC home visit and the upcoming services page

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#311]
Steps to replicate:

- Register an ANC woman (make her at least 13 weeks pregnant, so that IPTp-SP dose 1 is due)
- Record a home visit, marking that IPTp-SP dose 1 was given.
- Change the device date/time to 1 month in the future (when dose 2 should be due)
- Log back in and find the woman's profile. You'll see that the home visit and upcoming services page is saying dose 3 is due, not 2. Dose 2 is correctly shown on the ANC profile page though. See screenshots below.

To pass QA:
- All of the steps above must result in dose 2 being shown as due.
- The same works in both English and French versions of the app.

Screenshots:
![Screenshot_20191011-155226_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/65043698-1abc0f00-d964-11e9-8218-6dc0d94f714e.jpg)

![Screenshot_20191011-155127_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/65043738-345d5680-d964-11e9-83e1-e9c4069910cb.jpg)
![Screenshot_20191011-155201_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/65043777-450dcc80-d964-11e9-8e76-02373d8fbc49.jpg)

**Comment by cafootitt** [comment]
V1.0.6

lgtm

**Comment by cafootitt** [comment]
Sorry, closed this too soon.

When I changed the date/time settings back to today's date, SP 3 dose appears.

Steps to replicate:
- Register an ANC woman (make her at least 13 weeks pregnant, so that IPTp-SP dose 1 is due)
- Record a home visit, marking that IPTp-SP dose 1 was given.
- Change the device date/time to 1 month in the future (when dose 2 should be due)
- Log back in and find the woman's profile. The home visit and upcoming services page is saying dose 2 (which is correct).
- Change the device date/time settings back to today's date
- The app doesn't require login for some reason, so I go to the woman's profile, and the SP 3 dose is appearing now.

**Comment by AnnieMungai** [comment]
v1.0.11 Togo release candidate

Looks good!
