### ISSUE TITLE
Pregnancy outcome of "Miscarriage" causes the app to crash

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#326]
When you navigate to their profile on their family page, the app crashes.

To replicate:
1. Take an ANC woman
2. Fill in her pregnancy outcome forms as Miscarriage
3. Navigate to her family page
4. Select her name to go to her profile
5. App crashes

Similar to https://github.com/OpenSRP/opensrp-client-chw-anc/issues/266

**Comment by cafootitt** [comment]
Yea, makes sense to work on https://github.com/OpenSRP/opensrp-client-chw-anc/issues/266 as well when this issue is picked up. I'll move them next to each other in the to do column. Thanks Megan.

**Comment by msschroeder** [comment]
lgtm
