### ISSUE TITLE
Immunizations at birth in PNC home visit not working correctly

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#330]
- [x] The task appears even if the BCG and OPV was select in the Pregnancy outcome form
- [x] If you did select BCG and OPV in the Pregnancy outcome form, the task still appears, and you select BCG and OPV0 again, in the next visit the immunizations at birth will appear but you cannot select anything (shown below) - meaning you cannot complete the home visit.

![Screenshot_20190927-202141](https://user-images.githubusercontent.com/20777928/65267245-4d5d3780-db1d-11e9-9ea9-a336083ae0f2.png)

To replicate:
1. Register a pregnancy with live birth
2. Have the be given the immunizations
3. Do a PNC home visit
4. Select both BCG and OPV0 to be given
5. Move time ahead and do another PNC home visit
5. Fill in Immunizations at birth - you cannot submit the home visit due to this issue

**Comment by cafootitt** [comment]
@paulinembabu Do you think this was fixed in your latest update about the immunization task shouldn't be appearing in PNC visit?

**Comment by msschroeder** [comment]
QA November 18:
- [ ]  The task appears even if the BCG and OPV was select in the Pregnancy outcome form

**Comment by msschroeder** [comment]
lgtm - Thanks everyone!
