### ISSUE TITLE
What happens if a mother dies giving birth, but the child lives

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#351]
New Edge Case:
- Question: What happens when a mother dies in child birth but the child lives? What does that work flow look like?
- This is a new outcome that I don't think we thought of. 
- Additional questions we may want to consider:
  - What happens right now if the mother is marked as deceased in PNC?
  - Does the child record also get closed? 
  - Does the child move immediately to Child? 
  - Does the child move to Child at day 29? 
  - Can the PNC home visit be done for just the child?

The expected workflow:
- Add a field to pregnancy outcome form about the mother's condition (alive, dead)
- If mother is dead and child alive, the child record moves immediately to the Child register. 

What are your thoughts? @rowo @cafootitt @mberg

**Comment by rowo** [comment]
Saw this after the related [death-during-PNC issue](https://github.com/OpenSRP/opensrp-client-chw-anc/issues/352).

Is there a reason to move the newborn to Child rather than PNC? Is it because the questions apply to both mother and child?

**Comment by msschroeder** [comment]
@rowo I think we were thinking of moving the child to the Child register because of how PNC is set up. We would have to change how this was done. Because right now, we only have women and their child in PNC, not children only. I don't think it is impossible, but would require a lot more work in PNC.

**Comment by rowo** [comment]
@msschroeder thanks. So in the [multiple baby issue](https://github.com/OpenSRP/opensrp-client-chw-anc/issues/158#issuecomment-547240679) we are also dealing with another repercussion of combining mother and child into a single PNC profile and it's come up that maybe we shouldn't be combining them after all. We might want to meet about this to discuss.

**Comment by msschroeder** [comment]
@rowo I will see if I can set up a meeting with all of us

**Comment by cafootitt** [comment]
Closing this issue.
We're introducing new business logic to handle all of these scenarios.

**Comment by rowo** [comment]
@cafootitt For posterity, please link the issue(s) that closes this
