### ISSUE TITLE
What happens if the mother or child dies during the first 28 PNC days

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#352]
- What happens when a mother or child dies during the first 28 days of PNC?

Current work arounds are not great:
- Mother dies - wait until the child reaches 29 days, then remove the mother from the family. You will have to fill in the Home visit with information.
- Child dies - wait until the child reaches 29 days, then remove the child from the family. You will have to fill in the Home visit with information.

What is the best way to implement this workflow? 
Ideas:
- Add a form to remove the child prior to the 28 days. The form can be to note whether the mother is dead, in which the child would be moved to the child register, or whether the child is dead, in which the mother would remain in PNC care without child.

@rowo @cafootitt @rkodev @manutarus @paulinembabu @allan-allay

**Comment by manutarus** [comment]
@msschroeder we have an option on PNC to remove the mother we can extend this this to allow moving the child to the child register when the mother is removed before the child is 28 days old,  I think we can add another option for removing the child as well

**Comment by rowo** [comment]
The whole point of this app is to combat high maternal or child mortality so I feel like this isn't such an edge case in our context. 

If Manu is saying the form already exists to remove someone, it seems okay to have someone in PNC whether it's a mother alone or a child alone. The PNC forms would need to be updated so the inappropriate questions are no longer asked or required.

**Comment by cafootitt** [comment]
Closing this.

based on recent discussions, we made the decision to include Remove Child forms for each child in the PNC profile menu. We will be creating separate issues to introduce new business logic around moving child to child register if mom dies before 28 days.

**Comment by rowo** [comment]
@cafootitt For posterity, please link the issue(s) that closes this
