### ISSUE TITLE
French strings missing for strings on the IPTp-SP/SP dose task in ANC home visit

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#362]
![Screenshot_20191114-113157_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/68843597-7216fb00-06d9-11ea-8d8c-1faa02321338.jpg)

**Comment by paulinembabu** [comment]
Kindly clarify what this string should be

**Comment by cafootitt** [comment]
@paulinembabu Can these be added in Transifex? If so, I'll add the translations there.

**Comment by AnnieMungai** [comment]
Liberia CFC Monitor App Version: 0.1.9 (6th Dec 2019)

Looks good.
