### ISSUE TITLE
French strings missing 

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#364]
These were fixed, but now they're not displaying in French again

![Screenshot_20191114-113751_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/68844321-a939dc00-06da-11ea-801d-774aebc82b6b.jpg)

**Comment by AnnieMungai** [comment]
![Screenshot_2019-12-03-11-29-42-13(1)](https://user-images.githubusercontent.com/58034047/70034310-04683b80-15c2-11ea-8d34-df5e28970ae3.png)

**Comment by AnnieMungai** [comment]
On the infants profile - the french version - the infant's gender is appearing in english. This is also showing when you open the infants register homepage. 
![Screenshot_2019-12-03-11-28-57-45](https://user-images.githubusercontent.com/58034047/70034476-4c875e00-15c2-11ea-82dc-c62dedb963c9.png)

**Comment by cafootitt** [comment]
v1.0.11 Togo release candidate

lgtm
