### ISSUE TITLE
PNC visit button missing on some PNC profiles, but not all

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#368]
Stage server - moa login, V1.0.10, built on Nov 14th

We need to investigate why this is happening for this particular record. This is reported by UNICEF as well, so assigning high priority status.

![Screenshot_20191119-111340_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/69145686-416f0100-0adf-11ea-997a-4fde2c70115e.jpg)

![Screenshot_20191119-111344_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/69145732-62cfed00-0adf-11ea-863f-e1435a825e8e.jpg)

**Comment by paulinembabu** [comment]
We tried to Replicate the issue But was not able to.

**Comment by cafootitt** [comment]
Will reopen if we can find this issue again.
