### ISSUE TITLE
Women are still duplicated in ANC and PNC registers

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#370]
Guinea production server, asc1 login, play store version:

There are women appearing in both the ANC and PNC registers. You can re-record a pregnancy outcome for these women, and another baby is added to the profile page in PNC.

Client: Femme Dopavogui, ID: 1155167

**Comment by allan-allay** [comment]
From investigations we found out this happens in the following scenario: 

----
> Using a shared user(login) on different devices (suggesting a training setup or CHWs sharing credentials
On one device that's online, the user does the ANC registration and fills in the Pregnancy outcome form thus moving the woman to the PNC register. 
On a second offline device, the user does an ANC registration and the event is processed offline on the device. When this device comes online later, upon syncing the server deems the ANC registration as the latest event and the ANC registration is processed adding the woman to the ANC register resulting in the woman being in both registers.

----
 The above is an edge case which ideally shouldn't be happening with CHWs targetting different households and no shared edits on a single record

**Comment by cafootitt** [comment]
Thanks Allan, I'll close this, thanks for looking into it.
