### ISSUE TITLE
French Strings - chw-ANC - SP 1 dose

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-chw-anc#381]
Liberia CFC Monitor App Version: 0.1.9 (6th Dec 2019)
On the french version -ANC module - SP1 dose is in English on the upcoming services list and the medical history profiles. Check client: Marcha Le Roux.

![IMG_20191206_122725](https://user-images.githubusercontent.com/58034047/70316308-8065bc00-182c-11ea-9414-fe595283164c.jpg)
![IMG_20191206_122854](https://user-images.githubusercontent.com/58034047/70316319-8491d980-182c-11ea-8273-4d03ba356b66.jpg)

**Comment by cafootitt** [comment]
@AnnieMungai I think I misunderstood this issue. This is actuallly fine in French. Closing this.
