### ISSUE TITLE
Location exports for Liberia and Guinea formatted in CSV

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#382]
Just like we did for Togo, we need to do the CSV location data export for Canopy.

**Comment by rkodev** [comment]
Location Extraction Script

# script to verify all the locations have tags

select name , uuid from location where retired = 0 and location_id not in (
select ltm.location_id from  location_tag_map ltm  inner join location_tag lt on lt.location_tag_id = ltm.location_tag_id
where lt.retired = 0
);

**Comment by rkodev** [comment]
# script to extract all TOGO locations
select l.uuid location_id , l.name location_name , lt.name location_type , p.uuid parent_id, p.name parent_name 
from location l
left join location p on p.location_id = l.parent_location and p.retired = 0
inner join location_tag_map ltm on ltm.location_id = l.location_id
inner join location_tag lt on lt.location_tag_id = ltm.location_tag_id and lt.retired = 0
where lt.name in ('National', 'Regional' , 'District' , 'Formation sanitaire', 'Supervisor', 'Village')
and l.retired = 0
order by lt.location_tag_id desc;

**Comment by rkodev** [comment]
#script to extract all Guinea locations

select l.uuid location_id , l.name location_name , lt.name location_type , p.uuid parent_id, p.name parent_name 
from location l
left join location p on p.location_id = l.parent_location and p.retired = 0
inner join location_tag_map ltm on ltm.location_id = l.location_id
inner join location_tag lt on lt.location_tag_id = ltm.location_tag_id and lt.retired = 0
where lt.name in ('Country' , 'Region' , 'Prefecture' , 'Commune' , 'Health Facility' , 'Village')
and l.retired = 0
order by lt.location_tag_id desc;

**Comment by rkodev** [comment]
# script to extract all Liberia locations

select l.uuid location_id , l.name location_name , lt.name location_type , p.uuid parent_id, p.name parent_name 
from location l
left join location p on p.location_id = l.parent_location and p.retired = 0
inner join location_tag_map ltm on ltm.location_id = l.location_id
inner join location_tag lt on lt.location_tag_id = ltm.location_tag_id and lt.retired = 0
where lt.name in ('Country' , 'County' , 'District', 'Clinics', 'CHSS', 'Village')
and l.retired = 0
order by lt.location_tag_id desc;
