### ISSUE TITLE
Modify PNC profile to show multiple babies

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#394]
<img width="291" alt="Screen_Shot_2020-01-09_at_2_24_59_PM" src="https://user-images.githubusercontent.com/20777928/72064763-9e23b680-32ed-11ea-9bb7-f197683c6804.png">

- [x] Update the text under the avatar to include all the babies names:

{first_name} {middle_name} {surname}, {age}, {sex}
{first_name} {middle_name} {surname}, {age}, {sex}
Etc.

- [x] The first set of names and age belong to the mother
- [x] The second set of names, age, and sex below to the first child
- [x] All proceeding sets of names, age, and sex below to the next iteration of the child as they were entered in the pregnancy outcome form
- [x] The order the children appear are in alphabetical order

**Comment by cafootitt** [comment]
WCARO QA:

- [ ] It's a small thing, but can we center-align all of the names? Right now they are left-aligned.

**Comment by msschroeder** [comment]
BA QA Jan 31 Build:
- [ ] Center aligning is fine for BA too.

**Comment by cafootitt** [comment]
QA 18 Feb - lgtm
