### ISSUE TITLE
Remove the colored circle around PNC avatar when there are multiple babies

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#397]
- [x] Remove the colored circle around the PNC avatar when {no_children} > 1 (WCARO) or {no_children_no} > 1 (BA)

**Comment by cafootitt** [comment]
Wcaro QA:

- [ ] Can we remove the outline entirely from the avatar? It's quite thick and cutting off most of the avatar itself.

![Screenshot_20200204-092506_CFC-RTM - Togo](https://user-images.githubusercontent.com/3488986/73719389-59ded700-4730-11ea-9388-4b9de13731c4.jpg)

**Comment by msschroeder** [comment]
BA QA Jan 31 Build:
- [ ] Please do the same to BA: Can we remove the outline entirely from the avatar? It's quite thick and cutting off most of the avatar itself.

**Comment by paulinembabu** [comment]
Yes we Can remove it

**Comment by cafootitt** [comment]
Closing this and creating a new issue for clean up: https://github.com/OpenSRP/opensrp-client-chw-anc/issues/413
