### ISSUE TITLE
Add tasks for multiple babies in PNC home visit

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#398]
- [x] Add all PNC home visit tasks for each child
- [x] Child tasks in PNC home visit for child (BA): 

PNC HOME VISIT | Medical history? | Mother | Baby
-- | -- | -- | --
Danger signs - mother |   | Yes | No
Danger signs - baby |   | No | Yes
PNC health facility visits | Yes | Yes | No
Family Planning | Yes | Yes | No
Immunizations (at birth) | Yes | No | Yes
Exclusive breastfeeding | Yes | No | Yes
Counselling |   | Yes | No
Nutrition status - Mother - optional | No | Yes | No
Nutrition status - Baby - optional | No | No | Yes
Malaria prevention |   | Yes | No
Observations & Illness - Mother |   | Yes | No
Observations & Illness - Baby |   | No | Yes

- [x] Child tasks in PNC home visit for child (WCARO):

PNC HOME VISIT | Medical history? | Mother | Baby
-- | -- | -- | --
Danger signs - mother |   | Yes | No
Danger signs - baby |   | No | Yes
PNC health facility visits | Yes | Yes | No
Child vaccine card received | Yes | No | Yes
Immunizations (at birth) | Yes | No | Yes
Umbilical cord care |   | No | Yes
Exclusive breastfeeding | Yes | No | Yes
Kangaroo Mother Care (KMC) (LBW babies only) |   | No | Yes
Family Planning | Yes | Yes | No
Observations & Illness - Mother |   | Yes | No
Observations & Illness - Baby |   | No | Yes

- [x] Differentiate the tasks by using the child's name (as we are currently doing)
- [x] All baby tasks for one baby would appear together, like so:

Task 1 - Baby 1
Task 2 - Baby 1
Task 3 - Baby 1

Task 1 - Baby 2
Task 2 - Baby 2
Task 3 - Baby 2

Etc.

**Comment by cafootitt** [comment]
QA WCARO:

- [ ] KMC task is not appearing for LBW babies

Steps to replicate:
- Record pregnancy outcome
- Number of children born is 2
- Make each child LBW = yes
- Open PNC visit
- KMC should appear for each child, but it doesn't

- [ ] Immunizations recorded in Pregnancy Outcome form not reflected correctly in PNC visit

Steps to replicate:
- Record pregnancy outcome
- Number of children born is 2
- Give first child OPV 0 and leave BCG blank
- Give the second child BCG and leave OPV 0 blank
- Open PNC home visit
- Second child correctly shows only OPV 0 due
- But the first child shows both OPV 0 and BCG due, when it should only show BCG

@Mstjamush Can you help write tests for this, as this is not the first time that vaccines and KMC task has broken. Thanks.

**Comment by msschroeder** [comment]
QA BA:
- [ ] Title for mother nutritional task should be "Nutritional status - mother - optional
- [ ] Immunizations are not working correctly for Immunization task for any baby

Findings:
- I selected all 3 babies with BCG and OPV 0 given at birth. All three have a task for Immunizations at birth.

- [ ] Immunization task - I can select BCG, OPV O and No vaccine given in th PNC Home visit and SAVE

Replicate:
1. Add 3 babies
2. All have been given BCG and OPV O
3. Open PNC Home visit
4. Open Immunization app - select all three options

- [ ] Immunization task - All immunizations should NOT be selected when task first opens. Nothing should be selected. The user should have to select.

**Comment by cafootitt** [comment]
QA Wcaro 18 Feb:

- [ ] Immunizations recorded in Pregnancy Outcome form not reflected correctly in PNC visit
Steps to replicate:
- Record pregnancy outcome
- Number of children born is 2
- Give first child OPV 0 and leave BCG blank
- Give the second child BCG and leave OPV 0 blank
- Open PNC home visit
- Second child correctly shows only OPV 0 due
- But the first child shows both OPV 0 and BCG due, when it should only show BCG

This was not addressed.

**Comment by msschroeder** [comment]
QA Feb 18 Build:
QA BA:
- [ ] Title for mother nutritional task should be "Nutritional status - mother - optional
- [ ] Immunizations are not working correctly for Immunization task for any baby

Findings:
- I selected all 3 babies with BCG and OPV 0 given at birth. All three have a task for Immunizations at birth.

- [ ] Immunization task - I can select BCG, OPV O and No vaccine given in th PNC Home visit and SAVE

Replicate:
1. Add 3 babies
2. All have been given BCG and OPV O
3. Open PNC Home visit
4. Open Immunization app - select all three options

- [ ] Immunization task - All immunizations should NOT be selected when task first opens. Nothing should be selected. The user should have to select.

**Comment by cafootitt** [comment]
This now passes Wcaro QA - good work!

**Comment by msschroeder** [comment]
This looks great!
