### ISSUE TITLE
Modify PNC medical history page to allow for multiple babies

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#399]
See Marvel mockup with handoff notes: https://marvelapp.com/9j1277a/screen/64501182

- [x] Modify the medical history so each person (mother and each baby) have their own medical history
- [x] Order in the medical history: Last visit, Mother, Child 1, Child 2, ....
- [x] Mother's heading : {first_name} {middle_name} {surname} (Mother)
- [x] Child #1: {first_name} {middle_name} {surname} (Baby)
- [x] Child #2 {first_name} {middle_name} {surname} (Baby)
- [x] First set of names belong to the mother
- [x] Second set of names belongs to baby
- [x] All other set of names belong to proceeding babies in the order they were entered on the pregnancy outcome form.

**WCARO - SPECIFIC**
- [x] Please reference [this](https://docs.google.com/spreadsheets/d/11YsEYAXGr8aQUJm2vOKwTogyqj1XKsPwGboT-aKDpZA/edit#gid=0) to see what PNC tasks should appear in medical history:

PNC HOME VISIT | Medical history? | Mother | Baby
-- | -- | -- | --
Danger signs - mother |   | Yes | No
Danger signs - baby |   | No | Yes
PNC health facility visits | Yes | Yes | No
Child vaccine card received | Yes | No | Yes
Immunizations (at birth) | Yes | No | Yes
Umbilical cord care |   | No | Yes
Exclusive breastfeeding | Yes | No | Yes
Kangaroo Mother Care (KMC) (LBW babies only) |   | No | Yes
Family Planning | Yes | Yes | No
Observations & Illness - Mother |   | Yes | No
Observations & Illness - Baby |   | No | Yes

----------------------------------------------------------------------------------------------

**BA - SPECIFIC**
- [x] Under the mother heading, include a subheading "PNC health facility visits" and include all the PNC health facility information as it is currently included
- [x] Under the mother heading, include a subheading "PNC home visits" and include all the PNC home visit information as it is currently included
- [x] Under the mother heading, include a subheading "Family planning" and include all the Family planning information as it is currently included
- [x] Under each child heading, include the subheading "Immunizations" and include all the immunization information as it is currently included
- [ ] Under each child heading, include the subheading "Growth and nutrition" and include all the growth and nutrition information as it is currently included

PNC HOME VISIT | Medical history? | Mother | Baby
-- | -- | -- | --
Danger signs - mother |   | Yes | No
Danger signs - baby |   | No | Yes
PNC health facility visits | Yes | Yes | No
Family Planning | Yes | Yes | No
Immunizations (at birth) | Yes | No | Yes
Exclusive breastfeeding | Yes | No | Yes
Counselling |   | Yes | No
Nutrition status - Mother - optional | No | Yes | No
Nutrition status - Baby - optional | No | No | Yes
Malaria prevention |   | Yes | No
Observations & Illness - Mother |   | Yes | No
Observations & Illness - Baby |   | No | Yes

**Comment by cafootitt** [comment]
QA Wcaro: Overall, this looks good, but some fixes required:

- [ ] Let's simplify the child vaccine card received section to just the below:

![Screenshot_20200204-094048_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/73720574-5b5dce80-4733-11ea-9129-451221826ded.jpg)

- [ ] The data is not showing correctly for 2 of the 3 babies:

![Screen_Shot_2020-02-04_at_9_53_25_AM](https://user-images.githubusercontent.com/3488986/73721077-72e98700-4734-11ea-94a6-86249774198a.jpg)

![Screen_Shot_2020-02-04_at_9_55_42_AM](https://user-images.githubusercontent.com/3488986/73721164-ad532400-4734-11ea-98c8-5ea4eacb0ed5.jpg)

**Comment by msschroeder** [comment]
BA QA Jan 31st Build:
- [ ] Child received vaccination card should not appear in the medical history in PNC as this is not collected in the PNC home visit
![Screenshot_20200305-105159](https://user-images.githubusercontent.com/20777928/73826069-30947880-480e-11ea-8f98-54e1f584ba5e.png)

**Comment by allan-allay** [comment]
- Fixed issues as detailed above
- See below screenshots after fixes
----
WCARO 
![wcaro_mh_1](https://user-images.githubusercontent.com/16164649/73852147-c09ee600-483f-11ea-9566-e23cf953c000.png)
![wcaro_mh_2](https://user-images.githubusercontent.com/16164649/73852153-c4326d00-483f-11ea-8532-98f911a769a5.png)
----
BA 
![ba_mh](https://user-images.githubusercontent.com/16164649/73852205-d7453d00-483f-11ea-8fbb-9c05780ce6ae.png)

**Comment by cafootitt** [comment]
Wcaro QA 18 Feb:

This passes, but new issues cropped up, so I'm going to create a new issue for that here: https://github.com/OpenSRP/opensrp-client-chw-anc/issues/414

**Comment by msschroeder** [comment]
This passes for BA
