### ISSUE TITLE
Update business rule for child addition to child register 

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#400]
Current business logic for adding a child to the child register: https://github.com/OpenSRP/opensrp-client-chw-anc/issues/100

- [ ] Update the business logic to add a child(ren) to the child register earlier than 28 days if a PNC mother's record is closed - whether she dies or moves away.

Test case:
- Open an ANC woman's record and fill out the Pregnancy Outcome form:
-- Pregnancy outcome is live birth
-- Delivery date is 3 days ago
-- Number of children born is 2
-- Fill out the Baby Details for both babies
- Open the new record created in PNC
- On the PNC profile, in top right dropdown menu, tap on Remove this person
- Fill out the form (remove reason can be any of the 3 reasons)
- Submit the form

Expected results:
- PNC record is removed from the PNC register
- PNC tally in side menu goes down by one
- PNC icon in family register list is removed
- Woman's record is removed from the family profile members tab
- A record for the child(ren) gets created in the child register, sorted to the top of the list
- The Child register tally in the side menu goes up by the number of children who are added
- The child(ren) are added to the family profile members tab
- Home visits for the children added to the register list should become due immediately
- Child icons (blue or pink) get added to the family register list for each child

**Comment by cafootitt** [comment]
QA WCARO - Awesome work on this one! It passes QA!

**Comment by msschroeder** [comment]
Lgtm
