### ISSUE TITLE
Add Remove child options for each baby in top right PNC profile menu

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#401]
<img width="305" alt="72073411-e6000900-3300-11ea-9425-4d97aae5e43a_png__1080×1920_" src="https://user-images.githubusercontent.com/20777928/72161778-c8e73b00-33d1-11ea-83b9-28b2d7bd62f9.png">

- [ ] Modify the top right dropdown to show "Remove Baby {first_name} "
- [ ] WCARO: This should appear between " Edit Child Under 5" and "Remove this person"
- [ ] BA: This should appear between "FP initiation" and "Remove this person"
- [ ] Each child should have its own dropdown menu link from  "Remove Baby {first_name} "
- [ ] Each child's  "Remove Baby {first_name} " should appear in alphabetical order
- [ ] When the link is selected, it should go to the Remove a child/person form and work as it does for all other family members.

**Comment by cafootitt** [comment]
Passes QA for Wcaro

**Comment by msschroeder** [comment]
lgtm
