### ISSUE TITLE
Change the Remove this person to Remove mother

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#402]
<img width="431" alt="72073411-e6000900-3300-11ea-9425-4d97aae5e43a_png__1080×1920_" src="https://user-images.githubusercontent.com/20777928/72162267-b3264580-33d2-11ea-8ea8-fa1f4927828f.png">

- [x] When a mother is moved to the PNC register, change "Remove this person" to "Remove the mother"
- [x] When a mother is removed from the PNC register, change "Remove the mother" to "Remove this person"

**Comment by cafootitt** [comment]
Wcaro QA: lgtm

**Comment by msschroeder** [comment]
Closing - LG
