### ISSUE TITLE
Registration of 0(zero) kids should not be successful

### ISSUE THREAD

**Issue by Mstjamush** [OpenSRP/opensrp-client-chw-anc#408]
A user is currently allowed to save 0(zero) kids as a Pregnancy outcome. This should fail validation before saving

**Comment by cafootitt** [comment]
I think this would be addressed when we add the constraint to the number of children field of . > 0 and < 10, which is part of this issue QA: https://github.com/OpenSRP/opensrp-client-chw-anc/issues/393.

Since this is duplicated, I'm going to close this issue.
