### ISSUE TITLE
Design MLS in CHW app

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-chw-anc#48]
The WCARO/BA apps will need to support MLS (English and French, English and Swahili), similar to how the Mauritania project has implemented it.

Ideally, the language switcher should be a setting for the country-specific app. For e.g. Liberia will not need a language switcher, as their app will be only in English, but all other countries in West Africa (and TZ) will require a language switcher feature in the app.

Mauritania has it in the left-hand navigation drawer. I think we can probably do something similar for WCARO. 

Current left hand navigation drawer for CHW app:

![Screenshot_20190603-105451](https://user-images.githubusercontent.com/3488986/58785499-42be7700-85ee-11e9-9640-efb5513bae07.png)

@rowo Assigning to you. This issue is to finalize the placement of the ML switcher for CHW app. Once we have a final determination, I'll re-assign for implementation.
Thanks.

**Comment by rowo** [comment]
I'd like to rearrange this menu with these updates, if feasible. The reasoning is it gets a bit noisy with so many elements and levels, so I just put them all on the same level except for Sync.

![Register Menu](https://user-images.githubusercontent.com/1584163/58968858-bc886900-8784-11e9-8fca-12b48021d5ac.png)

**Comment by cagulas** [comment]
Thanks Roger.
