### ISSUE TITLE
Implement ANC Upcoming Services page for BA

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#53]
The Upcoming Services page for ANC will appear the same way as in the Child's profile's View upcoming services row. The original due date of the service displays, followed by number of days overdue (in red) or number of days until due, followed by service name. We are capturing only 1 type of service in the ANC upcoming services page for BA: ANC health facility visit. See below.

<img width="493" alt="Screen_Shot_2019-06-04_at_12_36_58_PM" src="https://user-images.githubusercontent.com/20777928/58871050-fa748700-86c9-11e9-8a64-1461afac6213.png">

Linked to #51

**Comment by msschroeder** [comment]
@rkodev I was just wondering how does the health facility calculate the next visit, like in the upcoming services. Do you have to go to the first health facility visit before the second health facility appears? Also, how does that affect the calculation of the others? I would be happy to discuss more in person.

**Comment by mberg** [comment]
I don’t think we were doing upcoming service scheduling for the facility.
This would just be for expected pregnancy outcome I think

**Comment by msschroeder** [comment]
@mberg It was more to provide reminders for the health facilities. This was being done in the home visit and then made sense to include here as well. This was what was also being done in WCARO. So it was an added consistency between them. Is this something we should remove @mberg ?

**Comment by rkodev** [comment]
@msschroeder the next visit date should appear after registration in PNC and not after the 1st visit.

**Comment by msschroeder** [comment]
@rkodev The upcoming services are not calculating the number of days over correctly. For example, in the screenshot below. She is due on the 28th of Sept 2019, but today was Sept 14th, 2019. 

![Screenshot_20190914-115140](https://user-images.githubusercontent.com/20777928/62525995-0e12aa00-b841-11e9-8534-0215d0fa05e2.png)

**Comment by msschroeder** [comment]
lgtm
