### ISSUE TITLE
Rearrange and add language switcher to left navigation drawer

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#54]
We are adding multi-language support to the app. We will need to rearrange the the items in the left hand navigation drawer to do this. Please see the mockup below. Note that HIV is incorrect in the mockup. Instead of HIV, PNC should be shown after ANC, so the order should be: Families, ANC, PNC, Child.

![58968858-bc886900-8784-11e9-8fca-12b48021d5ac](https://user-images.githubusercontent.com/3488986/59012794-13ec0f00-8841-11e9-994a-fe2e9a2f85c5.png)

------------------------------------------------------------------------------------------------------

BA: Please note that the multi-language support will be added for BA (English - Swahili). The set up will be the same as WCARO (see the mock-up above), but the registers will be different. The registers will be: All Families, ANC, PNC, Child Clients, FP, Malaria.

**Comment by rkodev** [comment]
@rowo could you please provide the 3 icons below for language, the device to device sync and logout

**Comment by rkodev** [comment]
@rowo @cafootitt the functionality has been implemented. The 3 icons will be updated when ready

**Comment by rowo** [comment]
@rkodev Here you go. I also added to the [de facto icon Drive folder](https://drive.google.com/open?id=1XMVd5PJEZEanMs57tBgEWbhVJbRBNYG3)

![sidemenu-logout](https://user-images.githubusercontent.com/1584163/59927889-7af5f000-940b-11e9-8576-de269e35d61a.png)
![sidemenu-language](https://user-images.githubusercontent.com/1584163/59927891-7b8e8680-940b-11e9-830b-bcbf14684b23.png)
![sidemenu-p2p](https://user-images.githubusercontent.com/1584163/59927892-7b8e8680-940b-11e9-8228-b9ff9904bb62.png)

**Comment by rkodev** [comment]
@rowo thanks

**Comment by cafootitt** [comment]
lgtm
