### ISSUE TITLE
Implement due only filter in PNC register

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#59]
Exactly the same functionality as in family, child, and ANC registers: https://github.com/OpenSRP/opensrp-client-chw/issues/41.

-----------------------------------------------------------------------------------------------
BA: No difference from this.

**Comment by cafootitt** [comment]
@rkodev What question do you have on this?

**Comment by rkodev** [comment]
@cafootitt this was resolved.

**Comment by msschroeder** [comment]
lgtm
