### ISSUE TITLE
Add the ANC register page

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#6]
<img width="536" alt="Screen_Shot_2019-04-19_at_4_40_42_PM" src="https://user-images.githubusercontent.com/3488986/56426961-d0eed000-62c2-11e9-99c5-128325187759.png">

Once the woman is registered, she'll appear at the top of the list. The fields shown come from the original family head/family member registration form and the ANC Registration form.

Everything else (search bar, side menu button, due only filter, bottom nav bar) should be exactly as in the Family and Child register pages.

------------------------------------------------------------------------------------------------------
BA
- [x] The data visualized on the screen for each client will use different values:
        {first_name} {middle_name} {surname}
        Age: {age}, GA: {gest_age} weeks
        {fam_village}

**Comment by cagulas** [comment]
QA 6 June build:

![Screenshot_20190607-102246](https://user-images.githubusercontent.com/3488986/59087930-c8079b80-890e-11e9-8f71-a8d25aa41486.png)

**Comment by msschroeder** [comment]
QA 6 June Build BA:
![Screenshot_20190611-094101__1_](https://user-images.githubusercontent.com/20777928/59249646-ec74b800-8c2d-11e9-9987-031b8eb7422d.png)

**Comment by rkodev** [comment]
![Screenshot_1560332173](https://user-images.githubusercontent.com/43806892/59340450-b4917180-8d0e-11e9-9c87-164c52849d2a.png)
@cafootitt fixed this issue

**Comment by cafootitt** [comment]
lgtm.

@msschroeder Closing this issue, as it will be fixed in both apps automatically.
