### ISSUE TITLE
Remove the lmp calculation from ANC Reg form

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#61]
Let's remove this in both the ANC Reg and the Edit ANC Reg forms.

![Screenshot_20190607-094726](https://user-images.githubusercontent.com/3488986/59086302-03539b80-890a-11e9-8c55-a77211365448.png)

**Comment by msschroeder** [comment]
For consistency, you can also remove this for BA

**Comment by cafootitt** [comment]
lgtm. 

@msschroeder Will close, since this would be automatically fixed in both versions.
