### ISSUE TITLE
ANC Clients count in left navigation drawer not updating

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#63]
On the new release (June 6 build date), I registered a new ANC woman (Martha Berg), yet the ANC Clients count remained at 0 in the left hand navigation drawer.

**Comment by msschroeder** [comment]
The same is true in BA. I registered two women. They appear in the ANC register, but not in the count on the left hand navigation drawer.

**Comment by cafootitt** [comment]
Fixed.
