### ISSUE TITLE
ANC record profiles are different between family and ANC register

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#65]
<img width="592" alt="Screen Shot 2019-06-07 at 12 11 34 PM" src="https://user-images.githubusercontent.com/3488986/59093803-7a465f80-891d-11e9-922f-b7cde9894724.png">

This is the same woman's profile. The screenshot on the left is the profile you see when you open the woman's profile from the ANC register. The screenshot on the right is the profile you see when you open the woman's profile from the family members page in the family profile.

We need to update this, so that the ANC profile is the same (should be the profile on the left) regardless of which navigation you take to open the woman's profile.

**Comment by msschroeder** [comment]
The same is true on BA. However, I would add the only difference expected on the profile page would be the "Return to..." which would be dependent on where the user just came from the All Families Register or ANC Register.

**Comment by cafootitt** [comment]
@manutarus I'm still not seeing this in the release that ronald shared this morning. Please work with him to get this work merged in.

**Comment by msschroeder** [comment]
@manutarus In the QA July 17th build, I did not see this implemented. They are still different profiles in the family and ANC register in BA

**Comment by cafootitt** [comment]
QA 30 July release:

<img width="498" alt="Screen Shot 2019-07-30 at 12 07 43 PM" src="https://user-images.githubusercontent.com/3488986/62116412-ca5cf500-b2c2-11e9-96cc-01b12b52108a.png">

Still not the same profile.

**Comment by msschroeder** [comment]
QA July 29th Build:
Same for BA - they are still not the same.

**Comment by cafootitt** [comment]
@manutarus Related PNC issue is here: https://github.com/OpenSRP/opensrp-client-chw-anc/issues/189.

**Comment by cafootitt** [comment]
Passes QA in 11 Sept release
