### ISSUE TITLE
Add text for services provided on the completed ANC home visit page

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#66]
These instructions were left out in the original implementation issue, so let me provide them now. We need to show the data inputs for the services, not just the green or yellow check mark. See how we show data inputs for the Child Home Visit showing which services were provided and not provided:

![Screenshot_20190607-123059](https://user-images.githubusercontent.com/3488986/59095020-27ba7280-8920-11e9-81dc-0203cabb3ca3.png)

For the ANC home visit, I'm thinking of showing the following:
https://docs.google.com/document/d/1aH9MfxmITLiPRO6cnNdRx0L4paOvJZH76biamsk--qw/edit

@rowo @msschroeder Pls review and see if this makes sense before I assign it to the devs.

**Comment by rowo** [comment]
@cagulas I made some comments in the doc. The "Task given/done: yes" format is a bit different from the child immunizations — what is your thinking for changing that?

**Comment by cagulas** [comment]
@rowo Actually this matches the new Child vaccine card received field, where the input is just yes or no. This also matches the exclusive bf task, which is also just yes/no. So for questions that involve making an observation, the format seems to be yes/no, whereas, actual services provided is more specific and provides the date.

**Comment by rowo** [comment]
Ok, counseling is a service/action in that thinking because of the verb for CHW to give/do. The main idea for the immunization labels was to shorten the amount of text by summarizing. But up to you for this.

**Comment by cagulas** [comment]
Ok, but since we are not capturing a date for bf or anc card or bednet (these are just observations she needs to record during each home visit, i.e. is she doing this or not), we won't be able to say "given on [date]" which is why I kept it at yes/no.

**Comment by cagulas** [comment]
@rowo I've revised the document. Can you take another look?

**Comment by msschroeder** [comment]
@rowo @cafootitt I have also added the BA version of this. I tried to keep it as consistent as possible. Would you mind taking another review?

**Comment by cafootitt** [comment]
@msschroeder I provided some feedback. All looks ok. I've created the implementation issue for wcaro here: https://github.com/OpenSRP/opensrp-client-chw-anc/issues/71. Please create a separate issue for BA or just append to issue 71 and then close this issue when you're finished.

**Comment by msschroeder** [comment]
Created an issue. Closing the issue.
