### ISSUE TITLE
Implement search bar parameters and search function

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-chw-anc#7]
Pretty much the same as child register list (https://github.com/OpenSRP/opensrp-client-chw/issues/12), i.e. search parameters are: 

- {surname}, {first_name}, or {middle_name} of the WRA
- {opensrp_id} of the WRA

------------------------------------------------------------------------------------------------------
BA: No difference

**Comment by cagulas** [comment]
QA June 6 build:

- [ ] I'm unable to QA this, because whenever I start typing in a search parameter in the ANC register, the app closes. It doesn't crash, it just closes and I have to log in again.

**Comment by msschroeder** [comment]
QA 6 June build:
- [ ] Same is true in BA

**Comment by cafootitt** [comment]
QA 19 June release:

- [ ] App isn't crashing anymore, so I'm able to test the search. However, it doesn't seem that {opensrp_id} of the WRA was added as a search parameter, or it's not working yet. Please check.

**Comment by rkodev** [comment]
@cafootitt on the previous release you had to type the whole number to get a match. I've updated this to search with a part number match

**Comment by cafootitt** [comment]
ah got it, thanks for letting me know.

**Comment by cafootitt** [comment]
lgtm
