### ISSUE TITLE
Implement the All Families register tasks due button logic

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#72]
Since a family may have more than one due task at any given time, we need to update the logic and UI of the task button in the family register, i.e. this button:

![Screenshot_20190826-122232_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/63680473-729ba600-c7fc-11e9-9eb8-4646ac1e8f76.jpg)

### List of possible tasks that would be due for the family:
**Both WCARO/BA:**
- Child home visit
- ANC home visit 
- PNC home visit 

**WCARO only:**
- WASH task

**BA only:**
- Malaria follow-up
- Referral follow up
(more will be added later once we add more registers to BA, e.g. FP)

### Implementation instructions
In the **All Families** register:
- [x] The visit button will display a number only (i.e. 1, 2, 3, etc.) which will represent the total number of tasks due for the family (See Figure 1)
- [x] The visit button will be **red** if **at least one** of the tasks are overdue (See Figure 1)
- [x] The visit button will be **blue** if **at least one** of the tasks are due AND none of the tasks are overdue (See Figure 1)
- [x] The button will say, "Tasks done" in green text when all tasks have been completed. This status would remain in place until at least one task becomes due/overdue, in which case, the button would turn blue or red (as per the rules above)
- [x] The button will say, "Tasks not done" in yellow text if every single due/overdue task in the family was marked as not done for that month (Note: Please keep in mind that some tasks, like PNC home visit and WASH task, do not have a "visit not done" status)
- [x] When the button is tapped, it will take you to the Due tab of the family profile (see Figure 2) - this should already be in place.

**Figure 1**

<img width="334" alt="Screen Shot 2019-06-12 at 11 50 20 AM" src="https://user-images.githubusercontent.com/20777928/59338182-93c71d00-8d0a-11e9-89bd-b3da143bdc16.png">

**Figure 2**

![Screenshot_20190612-120606](https://user-images.githubusercontent.com/20777928/59338250-b8bb9000-8d0a-11e9-9b55-337e4bd3c6af.png)

**Comment by cafootitt** [comment]
@msschroeder No, I don't think so. The Tasks Done status would remain shown until the next task becomes due. We decided this, because the due date for everything (at least all home visits) is the first of the calendar month, so no need to show this for every single row.

**Comment by cafootitt** [comment]
@msschroeder Also added the rule for tasks not done status.

**Comment by msschroeder** [comment]
@cafootitt Looks good

**Comment by cafootitt** [comment]
QA V1.0.4:

- [ ] **[I am not seeing this in the app (V1.0.4)]** The button will say, "Tasks done" in green text when all tasks have been completed. This status would remain in place until at least one task becomes due/overdue, in which case, the button would turn blue or red (as per the rules above)
- [ ] **[I am not seeing this in the app (V1.0.4)]** The button will say, "Tasks not done" in yellow text if every single due/overdue task in the family was marked as not done for that month (Note: Please keep in mind that some tasks, like PNC home visit and WASH task, do not have a "visit not done" status)
- [ ] I'm finding some inconsistencies between the number shown on the button vs. the number of due tasks shown on the Family profile Due tab. See below. The number shown on the family register due button should ALWAYS match the number of due tasks in the family profile due tab.

![Screenshot_20190917-143110_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/65038269-446f3900-d958-11e9-83e9-2848d2ffeb27.jpg)

![Screenshot_20190917-143047_CFC-RTM_-_Togo](https://user-images.githubusercontent.com/3488986/65038288-54871880-d958-11e9-978b-00ef7fbc24a4.jpg)

**Comment by cafootitt** [comment]
@paulinembabu Good work on this. The only thing that's left is the Tasks not done. I'll create a new issue for this.
