### ISSUE TITLE
Implement record PNC visit button row in PNC profile

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#75]
PNC will be implemented slightly differently than the Child/ANC Home visits.

On the PNC profile page, the visit buttons in the top row have various states:

![49637281-fcf56d00-fa15-11e8-88ae-7f510d8eff33](https://user-images.githubusercontent.com/3488986/60770503-cc200800-a0ca-11e9-80cc-686dffe3e2c6.jpg)

- [x] Please change the button text to "Record PNC visit" instead of "Record visit"
- [x] Remove the Visit not done option. We're not supporting this for PNC.
- [x] This is the starting state for all home visits. When a PNC woman becomes due for a PNC home visit is dependent on the [service schedule for the PNC home visit](https://docs.google.com/spreadsheets/d/1N86y-1TKokvWb0AsTPXH-d6cY4XFFP6wbiOc3-yzk5o/edit?usp=sharing) - PNC Home Visits tab. When a woman is first registered as PNC, this will automatically be their profile page visit status.
- [x] The blue record visit button opens the PNC home visit

<img width="337" alt="screen shot 2018-12-07 at 11 51 51 am" src="https://user-images.githubusercontent.com/3488986/49637478-8b69ee80-fa16-11e8-8a48-ebfc2a1baf8b.png">

- [x] Above is the overdue state of the visit button.
- [x] Tapping on the red Record PNC visit button launches the PNC home visit

<img width="295" alt="Screen_Shot_2019-06-13_at_4_03_18_PM" src="https://user-images.githubusercontent.com/20777928/59434932-30fe8000-8df5-11e9-80ac-69173688c431.png">

- [x] The above state is a temporary state only. For the 24 hours after a home visit is recorded, the user will see the above status. After 24 hours, the status changes (see next image below).
- [x] Use the PNC day [{today}-{delivery_date}} of the visit done
- [x] Tapping on the edit button launches the form that they submitted previously, where they can make edits.

<img width="377" alt="screen shot 2018-12-07 at 11 56 39 am" src="https://user-images.githubusercontent.com/3488986/49637696-2d89d680-fa17-11e8-983b-09e114f7650c.png">

- [ ] Finally, the last state above, is the state after the 24 hour period that a form was submitted. This essentially allows the user to submit another home visit before the next one is due.
- [ ] Tapping on this button opens the PNC home visit (a new one)
- [x] The button status changes again and becomes blue (see first image in this issue), when the PNC women becomes due for her next home visit - [service schedule for the PNC home visit](https://docs.google.com/spreadsheets/d/1N86y-1TKokvWb0AsTPXH-d6cY4XFFP6wbiOc3-yzk5o/edit?usp=sharing)- PNC Home Visits tab.

------------------------------------------------------------------------------------------------------

- [x]  **Different schedule in BA**: When a PNC women become due for an PNC home visit is dependent on the [service schedule for the PNC home visit](https://docs.google.com/spreadsheets/d/1qXErtcHbgiItLvVtdrg3V7oqiwC010fKtO7APIPxACY/edit?usp=sharing) in the CHW 3 - Service Schedule tab. When a woman is first registered as PNC, this will automatically be their profile page visit status.

**Comment by msschroeder** [comment]
Waiting for @cafootitt to provide thoughts on the above, then @msschroeder will update accordingly. Assigning to both.

**Comment by cafootitt** [comment]
@msschroeder I think we won't have a visit not done option here, simply because the visit schedules are not monthly, and the visits expire. Thanks for checking. I'm updating the issue above, but please check.

**Comment by msschroeder** [comment]
@cafootitt Looks good

**Comment by msschroeder** [comment]
@cafootitt via @paulinembabu This part, Finally, the last state above, is the state after the 24 hour period that a form was submitted. This essentially allows the user to submit another home visit before the next one is due.

If we allow the visit to be recorded outside the window of the day that it's due.. what should the Visit that is done be Tagged as?

I think it would be tagged by "Use the PNC day [{today}-{delivery_date}} of the visit done". How are you tagging the other visits?

**Comment by paulinembabu** [comment]
I was tagging them using the visit English names provided in the data dictionary. 
ie.Day 1 visit, Day 3 visit, Day 8 visit, Day 21 - 27 visit and Day 35 - 41 visit depending on the window period

**Comment by paulinembabu** [comment]
We agreed to Remove the Record Home visit Button After the Visit Has been done.

**Comment by cafootitt** [comment]
@paulinembabu @msschroeder Sorry, I think I didn't fully comprehend your questions from earlier when we talked about this. We probably do want to allow the CHW to record additional PNC home visits outside of the official schedule. I'll close this issue, since it passes QA, and I'll wait a little bit to see if and when we should revisit this though
