### ISSUE TITLE
Design the medical history

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#76]
The PNC medical history page is similar to Child medical history page, in that the View medical history row in the profile shows up only after the first services are recorded for the woman in the home visit.

<img width="390" alt="Screen_Shot_2019-06-13_at_6_07_18_PM" src="https://user-images.githubusercontent.com/20777928/59444355-6364a900-8e06-11e9-8daa-859cb9b3333a.png">

We will use something similar to ANC (shown above):
@cafootitt Can you provide input on what information you would be showing here. 

------------------------------------------------------------------------------------------------------
- [ ] BA: I was thinking of including just: "PNC health facility visit [1-4]: [date]" & "PNC home visit [ 1 - 5]: [date]"

**Comment by msschroeder** [comment]
@rowo @cafootitt I have create the issue for BA #174. Please close @cafootitt once you have finished for WCARO.

**Comment by cafootitt** [comment]
Done: https://github.com/OpenSRP/opensrp-client-chw-anc/issues/191
