### ISSUE TITLE
Design of the avatar or photo of PNC mother and child

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#81]
For the PNC module, we now have a mother and child displayed together. There are a few questions regarding this new module:

1. Will there be a new avatar/photo for this period of 28 days when the mother and child are together? If so, do we have the design for the new photo? 
2. If there is a photo of the mother, will that be used?

@cafootitt @rowo What are your thoughts?

**Comment by rowo** [comment]
I don't feel like we need to add this requirement and using the mother avatar placeholder and image would be ok with me. 

However, I've made a PNC avatar (basically the ZEIR icon) if you think its worth the engineering time.

![rowavatar-pnc](https://user-images.githubusercontent.com/1584163/59575404-6e7b3b80-9089-11e9-8b30-70088707754f.png)

**Comment by msschroeder** [comment]
@rowo Cool. That was my thought too. I just wanted to check. Let me close this issue and add this to the original issue. Thanks.
