### ISSUE TITLE
Danger signs - mother task

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#84]
Danger signs - mother is the first task to complete in the home visit. It is required to complete before the home visit can be submitted. It is always in the home visit.

Please look at the Danger Signs section in the PNC Home Visit tab in the [data dictionary](https://docs.google.com/spreadsheets/d/1hZrD3P8X3YAd-JvlXdT4TGKWJ87NlaLKjJlPrJZFwMY/edit#gid=102133992).

This will be a native form widget.

------------------------------------------------------------------------------------------------------
- [x] **BA is the same:** Please look at the Danger signs - mother section in the CHW 1 - PNC HH Visit tab in the [data dictionary](https://docs.google.com/spreadsheets/d/1qXErtcHbgiItLvVtdrg3V7oqiwC010fKtO7APIPxACY/edit?usp=sharing).

**Comment by msschroeder** [comment]
@cafootitt Please review

**Comment by cafootitt** [comment]
Issue lgtm

**Comment by msschroeder** [comment]
JSON shared on Slack WCARO channel

Please note - This conversion does not support multiple languages or notes question types. So for Danger Signs, please revert to the data dictionaries for this information and review.

**Comment by msschroeder** [comment]
lgtm for BA
@cafootitt Can you check this for WCARO content? If it is okay, please feel free to close.

**Comment by cafootitt** [comment]
lgtm

**Comment by msschroeder** [comment]
Recent Build:
- [ ] The Danger Signs toaster message is not showing at all - similar to the Danger Signs - Baby. Please refer to the [data dictionary](https://docs.google.com/spreadsheets/d/1qXErtcHbgiItLvVtdrg3V7oqiwC010fKtO7APIPxACY/edit?usp=sharing). I have highlighted the row in pink.

**Comment by cafootitt** [comment]
2 Sept release - passes Wcaro qa

@msschroeder Please QA and close and move to Done column if ok in BA

**Comment by cafootitt** [comment]
@msschroeder Please re-open or create a new task if this is still an issue in BA.
