### ISSUE TITLE
Danger signs - baby task

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#85]
Danger signs - baby is the second task to complete in the home visit. It is required to complete before the home visit can be submitted. It is always in the home visit.

Please look at the Danger Signs section in the PNC Home Visit tab in the [data dictionary](https://docs.google.com/spreadsheets/d/1hZrD3P8X3YAd-JvlXdT4TGKWJ87NlaLKjJlPrJZFwMY/edit#gid=102133992).

This will be a native form widget.

------------------------------------------------------------------------------------------------------
- [x] **BA is the same:** Please look at the Danger signs - mother section in the CHW 1 - PNC HH Visit tab in the [data dictionary](https://docs.google.com/spreadsheets/d/1qXErtcHbgiItLvVtdrg3V7oqiwC010fKtO7APIPxACY/edit?usp=sharing).

**Comment by msschroeder** [comment]
@cafootitt Please review

**Comment by cafootitt** [comment]
issue lgtm

**Comment by msschroeder** [comment]
JSON shared on Slack WCARO channel

Please note - This conversion does not support multiple languages or notes question types. So for Danger Signs, please revert to the data dictionaries for this information and review.

**Comment by msschroeder** [comment]
lgtm for BA
@cafootitt Can you check this for WCARO content? If it is okay, please feel free to close.

**Comment by cafootitt** [comment]
QA 13 Aug Togo release:

- [ ] The logic for the "Danger sign! /nRefer immediately to health facility." toaster is not working. The toaster alert message only appears if you select Convulsions and/or Jaundice danger signs, but none of the others. 
- [ ] Before moving to QA, please test that this works in both French and English versions

The relevance logic is below for easy reference:
{danger_signs_present} = Fast breathing OR Chest indrawing OR Low or high temperature OR Refuses to suckle OR No movement OR Convulsions OR Jaundice

**Comment by msschroeder** [comment]
QA 14 August Build: 
- [ ] The Danger signs toaster message does not appear at all for when any of the danger signs are selected for BA. I have highlighted them in pink in the [data dictionary](https://docs.google.com/spreadsheets/d/1qXErtcHbgiItLvVtdrg3V7oqiwC010fKtO7APIPxACY/edit?usp=sharing)

**Comment by cafootitt** [comment]
2 September release - 

@allan-allay I'm not seeing this fix for WCARO. Please refer to this comment: https://github.com/OpenSRP/opensrp-client-chw-anc/issues/85#issuecomment-521257756

**Comment by allan-allay** [comment]
Fixed this by adding missing checkbox attributes/options that are to be checked in the toaster relevance

**Comment by cafootitt** [comment]
lgtm
