### ISSUE TITLE
Family planning task

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#90]
**WCARO**

Family planning is the 9th task to complete in the PNC home visit for WCARO. It is required to completed before the home visit can be submitted.

This task will always appear in the home visit, until {fp_method} != "None"

Please look at the Family planning section in the PNC Home Visit tab in the [data dictionary](https://docs.google.com/spreadsheets/d/1hZrD3P8X3YAd-JvlXdT4TGKWJ87NlaLKjJlPrJZFwMY/edit#gid=1982829334).

This will be a native form widget.

________
**BA**

Family planning is the fourth task to complete in the home visit in BA. It is required to completed before the home visit can be submitted. It always appears in the home visit.

Please look at the Family planning section in the CHW 1 - PNC HH Visit tab in the [data dictionary](https://docs.google.com/spreadsheets/d/1qXErtcHbgiItLvVtdrg3V7oqiwC010fKtO7APIPxACY/edit?usp=sharing).

This will be a native form widget.

**Comment by cafootitt** [comment]
@msschroeder See my edits above, specifically about the point "This task will always appear in the home visit, until {fp_method} != "None""

BA is quite similar. Do you need the task to keep appearing in the home visit, even after the woman has accepted a FP method?

**Comment by msschroeder** [comment]
@cafootitt This makes sense. I have added this to the BA data dictionary

**Comment by msschroeder** [comment]
QA 14 August:
- [ ] Can we adjust the relevant condition for the last question `fp_start_date` so it only shows for {fp_method} = PPIUCD OR Pills OR Implant OR Condoms OR LAM OR Bead Counting OR Permanent (BLT) OR Permanent (Vascemtomy) 
instead of 
{fp_counseling} = "Yes"

Reference: CHW 1 - PNC HH Visit tab in the [data dictionary](https://docs.google.com/spreadsheets/d/1qXErtcHbgiItLvVtdrg3V7oqiwC010fKtO7APIPxACY/edit?usp=sharing)

**Comment by cafootitt** [comment]
@msschroeder Please open a new issue if there are still any issues for BA
