### ISSUE TITLE
Observation & Illness - Mother - optional task

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#96]
Observations & Illness - Mother - optional is the 10th task to complete in the home visit. It is NOT required to complete before the home visit can be submitted. It always appears in the home visit.

Please look at the Observations & Illness - Mother - optional section in the PNC Home Visit tab in the [data dictionary](https://docs.google.com/spreadsheets/d/1hZrD3P8X3YAd-JvlXdT4TGKWJ87NlaLKjJlPrJZFwMY/edit#gid=102133992). 

This will be a native form widget, same as what's already in the ANC module.

------------------------------------------------------------------------------------------------------
**BA is slightly different than WCARO**

Observations & Illness - Mother - optional is the tenth task to complete in the home visit. It is NOT required to complete before the home visit can be submitted. It always appears in the home visit.

Please look at the Observations & Illness - Mother - optional status section in the CHW 1 - PNC HH Visit tab in the [data dictionary](https://docs.google.com/spreadsheets/d/1qXErtcHbgiItLvVtdrg3V7oqiwC010fKtO7APIPxACY/edit?usp=sharing).

Please note the content is slightly different for BA

This will be a native form widget, same as what's already in the child module.

**Comment by msschroeder** [comment]
QA 29 July Build:
- Follow up question about other treatment is not included, if other treatment is selected for {action_taken_mama}. I have highlighted the row 133 in pink in the [data dictionary](https://docs.google.com/spreadsheets/d/1qXErtcHbgiItLvVtdrg3V7oqiwC010fKtO7APIPxACY/edit?usp=sharing).

**Comment by cafootitt** [comment]
@msschroeder Please open a new issue if there are still any issues for BA
