### ISSUE TITLE
Implement the service schedule for the PNC health facility visit task

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#98]
The PNC health facility visit schedule is used to trigger the PNC health facility visit task in the PNC home visit for WCARO (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/178) and BA (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/87), (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/88), and (https://github.com/OpenSRP/opensrp-client-chw-anc/issues/89).

**WCARO**

See the [service schedule dictionary](https://docs.google.com/spreadsheets/d/1N86y-1TKokvWb0AsTPXH-d6cY4XFFP6wbiOc3-yzk5o/edit?usp=sharing) - PNC health facility visits tab

----------------------------------------------------------------------------------------------------

**Different in BA**: See the [service schedule dictionary](https://docs.google.com/spreadsheets/d/1qXErtcHbgiItLvVtdrg3V7oqiwC010fKtO7APIPxACY/edit?usp=sharing) - CHW 4- HF PNC Visit Service Schedule tab

**Comment by cafootitt** [comment]
Passed QA for WCARO on (6 Sept build)

**Comment by cafootitt** [comment]
@msschroeder I'm closing this. Please re-open if any issues in BA.
