### ISSUE TITLE
Implement icon status for completed tasks in the PNC home visit - BA

### ISSUE THREAD

**Issue by msschroeder** [OpenSRP/opensrp-client-chw-anc#99]
Implement the coloring for a task of the PNC home visit:
- [x] Danger signs - mother: If {danger_signs_present_mama} record, then green check, otherwise yellow
- [x] Danger signs - baby:  If {danger_signs_present_child} record, then green check, otherwise yellow
- [x] PNC health facility visit - within 48 hours: If {pnc_visit_1} = "Yes", then green check, otherwise yellow
- [x] PNC health facility visit - days 3 - 7: If {pnc_visit_2} = "Yes", then green check, otherwise yellow
- [x] PNC health facility visit - days 8 - 28: If {pnc_visit_3} = "Yes", then green check, otherwise yellow
- [x] PNC health facility visit - days 29 - 42: If {pnc_visit_4} = "Yes", then green check, otherwise yellow 
- [x] Family planning: If {fp_counseling} = "Yes", then green check, otherwise yellow
- [x] Immunizations (at birth): If {opv0} and {bcg} are recorded, then green check, otherwise yellow
- [x] Exclusive breastfeeding 0 months: If {exclusive_breastfeeding0} = "Yes", then green check, otherwise yellow
- [x] Counselling: If {counselling_pnc} is recorded, then green check, otherwise yellow
- [x] Nutrition status: If {nutrition_status_mama} and {nutrition_status_1m} is recorded, then green check, otherwise yellow
- [x] Malaria prevention: If {fam_llin} = "Yes", then green check, otherwise yellow
- [x] Observations & illness - mother _- optional_ :If Observations & Illness - optional task is filled in, then green check, otherwise, leave blank
- [x] Observations & illness - baby _- optional_ :If Observations & Illness - optional task is filled in, then green check, otherwise, leave blank

**Comment by cafootitt** [comment]
@msschroeder I'm creating a separate issue for wcaro, thanks.

**Comment by msschroeder** [comment]
@cafootitt Great!

**Comment by msschroeder** [comment]
I have QAed and created new issue for any remaining bugs
